import { offsetIso } from "@/lib/datetime";
import type {
  ElevatesStore,
  Permission,
  PermissionKey,
  Role,
  RoleKey,
} from "@/types";

const roles: Role[] = [
  { id: "r-founder", key: "founder", name: "Founder", scope: "hq", description: "Full HQ authority" },
  { id: "r-hq-admin", key: "hq_admin", name: "HQ Admin", scope: "hq", description: "Organization operations" },
  { id: "r-hq-mentor", key: "hq_mentor", name: "HQ Mentor", scope: "hq", description: "Cross-chapter mentorship" },
  { id: "r-faculty", key: "faculty_coordinator", name: "Faculty Coordinator", scope: "chapter", description: "Faculty oversight" },
  { id: "r-chairman", key: "chairman", name: "Campus Lead", scope: "chapter", description: "Chapter executive lead (Campus Lead)" },
  { id: "r-vc", key: "vice_chairman", name: "Deputy Campus Lead", scope: "chapter", description: "Deputy executive" },
  { id: "r-sec", key: "secretary", name: "Secretary", scope: "chapter", description: "Events & operations" },
  { id: "r-js", key: "joint_secretary", name: "Joint Secretary", scope: "chapter", description: "Supports secretary" },
  { id: "r-coord", key: "elevates_coordinator", name: "Elevates Coordinator", scope: "chapter", description: "Cluster & program coord" },
  { id: "r-tech", key: "technical_team", name: "Technical Team", scope: "chapter", description: "Tech delivery" },
  { id: "r-media", key: "media_team", name: "Media Team", scope: "chapter", description: "Design & media" },
  { id: "r-cr", key: "class_representative", name: "Class Representative", scope: "chapter", description: "Class registrations & attendance" },
  { id: "r-student", key: "student", name: "Student", scope: "chapter", description: "Member" },
  { id: "r-alumni", key: "alumni", name: "Alumni", scope: "chapter", description: "Past member" },
  { id: "r-guest", key: "guest", name: "Guest", scope: "chapter", description: "External guest" },
  { id: "r-mentor", key: "industry_mentor", name: "Industry Mentor", scope: "chapter", description: "Industry guidance" },
];

const permissionDefs: { key: PermissionKey; name: string; description: string }[] = [
  { key: "org.manage", name: "Manage Organization", description: "Full HQ control" },
  { key: "chapter.create", name: "Create Chapter", description: "Spin up new chapters" },
  { key: "chapter.manage", name: "Manage Chapter", description: "Edit chapter settings" },
  { key: "leadership.manage", name: "Manage Leadership", description: "Leadership cycles" },
  { key: "class.manage", name: "Manage Classes", description: "Class divisions and representatives" },
  { key: "roles.manage", name: "Manage Roles", description: "Assign roles & permissions" },
  { key: "event.create", name: "Create Event", description: "Draft & publish events" },
  { key: "event.approve", name: "Approve Event", description: "Faculty/HQ event approval" },
  { key: "event.manage", name: "Manage Event", description: "Edit event details" },
  { key: "registration.review", name: "Review Registrations", description: "Representative review" },
  { key: "registration.approve", name: "Approve Registrations", description: "Secretary approval" },
  { key: "attendance.verify", name: "Verify Attendance", description: "Check-in students" },
  { key: "certificate.issue", name: "Issue Certificates", description: "Generate certificates" },
  { key: "report.submit", name: "Submit Reports", description: "Chapter reports" },
  { key: "report.approve", name: "Approve Reports", description: "HQ report approval" },
  { key: "report.download", name: "Download Reports", description: "Download approved reports as documents" },
  { key: "task.manage", name: "Manage Tasks", description: "Assign & track tasks" },
  { key: "resource.upload", name: "Upload Resources", description: "Library uploads" },
  { key: "announcement.publish", name: "Publish Announcements", description: "Broadcast messages" },
  { key: "analytics.view", name: "View Analytics", description: "Dashboards & scores" },
  { key: "student.register", name: "Register Students", description: "CR registration rights" },
];

const permissions: Permission[] = permissionDefs.map((p, i) => ({
  id: `p-${i + 1}`,
  ...p,
}));

const allPermIds = permissions.map((p) => p.id);
const permByKey = Object.fromEntries(permissions.map((p) => [p.key, p.id])) as Record<
  PermissionKey,
  string
>;

function allow(keys: PermissionKey[]) {
  return keys.map((k) => permByKey[k]);
}

const roleAllow: Record<RoleKey, PermissionKey[]> = {
  founder: permissionDefs.map((p) => p.key),
  hq_admin: permissionDefs.map((p) => p.key),
  hq_mentor: ["analytics.view", "report.approve", "announcement.publish"],
  faculty_coordinator: [
    "event.approve",
    "report.submit",
    "report.download",
    "analytics.view",
    "announcement.publish",
    "chapter.manage",
  ],
  chairman: [
    "chapter.manage",
    "leadership.manage",
    "class.manage",
    "event.create",
    "event.manage",
    "event.approve",
    "registration.review",
    "registration.approve",
    "attendance.verify",
    "certificate.issue",
    "report.submit",
    "report.download",
    "task.manage",
    "announcement.publish",
    "analytics.view",
    "roles.manage",
  ],
  vice_chairman: [
    "chapter.manage",
    "class.manage",
    "event.create",
    "event.manage",
    "registration.review",
    "registration.approve",
    "task.manage",
    "report.submit",
    "report.download",
    "analytics.view",
    "announcement.publish",
  ],
  secretary: [
    "class.manage",
    "event.create",
    "event.manage",
    "registration.approve",
    "attendance.verify",
    "certificate.issue",
    "task.manage",
    "report.submit",
    "report.download",
    "announcement.publish",
    "analytics.view",
  ],
  joint_secretary: [
    "event.create",
    "event.manage",
    "registration.review",
    "attendance.verify",
    "task.manage",
    "announcement.publish",
  ],
  elevates_coordinator: [
    "class.manage",
    "event.create",
    "event.manage",
    "registration.review",
    "attendance.verify",
    "task.manage",
    "announcement.publish",
    "analytics.view",
  ],
  technical_team: ["event.manage", "task.manage", "attendance.verify"],
  media_team: ["event.manage", "task.manage", "announcement.publish"],
  class_representative: [
    "student.register",
    "registration.review",
    "attendance.verify",
    "announcement.publish",
    "report.submit",
    "report.download",
  ],
  student: ["report.submit", "report.download"],
  alumni: [],
  guest: [],
  industry_mentor: ["analytics.view", "announcement.publish"],
};

const rolePermissions = roles.flatMap((role) => {
  const allowed = new Set(allow(roleAllow[role.key]));
  return allPermIds.map((permissionId) => ({
    roleId: role.id,
    permissionId,
    allowed: allowed.has(permissionId),
  }));
});

export function createSeedStore(): ElevatesStore {
  return {
    organization: {
      id: "org-1",
      name: "Elevates HQ",
      slug: "elevates",
      tagline: "Learn. Build. Grow. Ship. Repeat.",
      brandKit: {
        logoUrl: "/elevates-mark.svg",
        colors: {
          accent: "#f26430",
          charcoal: "#2d2d34",
          sage: "#5f7560",
          indigo: "#414066",
        },
      },
    },
    chapters: [
      {
        id: "ch-ekc",
        organizationId: "org-1",
        name: "EKC Chapter",
        slug: "ekc",
        college: "Eranad Knowledge City",
        city: "Manjeri",
        status: "active",
        healthScore: 94,
        memberCount: 186,
        eventCount: 13,
        projectCount: 8,
        foundedAt: "2024-08-01",
        facultyId: "u-faculty",
        notes: "Flagship chapter. Prioritize Build-A-Thon and cluster demos.",
      },
      {
        id: "ch-mes",
        organizationId: "org-1",
        name: "MES Chapter",
        slug: "mes",
        college: "MES College of Engineering",
        city: "Kuttippuram",
        status: "active",
        healthScore: 87,
        memberCount: 142,
        eventCount: 9,
        projectCount: 5,
        foundedAt: "2025-01-15",
      },
      {
        id: "ch-cusat",
        organizationId: "org-1",
        name: "CUSAT Chapter",
        slug: "cusat",
        college: "Cochin University of Science and Technology",
        city: "Kochi",
        status: "onboarding",
        healthScore: 72,
        memberCount: 64,
        eventCount: 3,
        projectCount: 2,
        foundedAt: "2025-11-01",
      },
    ],
    profiles: [
      {
        id: "u-founder",
        email: "founder@elevates.live",
        fullName: "Sarhan Qadir",
        department: "HQ",
        skills: ["Strategy", "Community", "Product"],
        interests: ["Open Source", "Education"],
        githubUrl: "https://github.com",
        linkedinUrl: "https://linkedin.com",
        points: 2400,
        badges: ["Founder", "Ship Captain"],
        bio: "Building the OS for student innovation communities.",
      },
      {
        id: "u-hq-admin",
        email: "admin@elevates.live",
        fullName: "Aisha Rahman",
        department: "HQ Ops",
        skills: ["Ops", "Analytics"],
        interests: ["Systems"],
        points: 1200,
        badges: ["HQ Admin"],
      },
      {
        id: "u-faculty",
        email: "faculty@ekc.edu",
        fullName: "Dr. Meera Nair",
        chapterId: "ch-ekc",
        department: "CSE",
        skills: ["Mentorship", "Research"],
        interests: ["AI", "Education"],
        points: 900,
        badges: ["Faculty"],
      },
      {
        id: "u-chairman",
        email: "chairman@ekc.elevates.live",
        fullName: "Arjun Menon",
        chapterId: "ch-ekc",
        department: "CSE",
        year: "4th Year",
        skills: ["Leadership", "Full Stack", "Public Speaking"],
        interests: ["Hackathons", "Startups"],
        githubUrl: "https://github.com",
        linkedinUrl: "https://linkedin.com",
        portfolioUrl: "https://elevates.live",
        points: 1880,
        badges: ["Campus Lead 2026", "Builder", "Top 1%"],
        engagementTier: "campus_lead",
        journeyStage: "leadership",
        bio: "Midnight coder. Chapter lead. Ships chaos into products.",
      },
      {
        id: "u-secretary",
        email: "secretary@ekc.elevates.live",
        fullName: "Diya Krishnan",
        chapterId: "ch-ekc",
        department: "ECE",
        year: "3rd Year",
        skills: ["Operations", "Event Design", "IoT"],
        interests: ["Hardware", "Community"],
        points: 1420,
        badges: ["Secretary", "Ops Ace"],
      },
      {
        id: "u-coord",
        email: "coord@ekc.elevates.live",
        fullName: "Rahul Dev",
        chapterId: "ch-ekc",
        department: "CSE",
        year: "3rd Year",
        skills: ["AI", "Python", "Workshops"],
        interests: ["ML", "Clusters"],
        points: 1100,
        badges: ["Coordinator"],
      },
      {
        id: "u-cr",
        email: "cr@ekc.elevates.live",
        fullName: "Naina Fathima",
        chapterId: "ch-ekc",
        department: "CSE",
        year: "2nd",
        section: "A",
        skills: ["Coordination", "Design"],
        interests: ["UI/UX"],
        points: 760,
        badges: ["Class Rep", "Girl Rep"],
      },
      {
        id: "u-cr-cse-boy",
        email: "cr.cse.boy@ekc.elevates.live",
        fullName: "Adil Rahman",
        chapterId: "ch-ekc",
        department: "CSE",
        year: "2nd",
        section: "A",
        skills: ["Coordination", "Events"],
        interests: ["Community"],
        points: 640,
        badges: ["Class Rep", "Boy Rep"],
      },
      {
        id: "u-cr-ece",
        email: "cr.ece@ekc.elevates.live",
        fullName: "Arjun Nair",
        chapterId: "ch-ekc",
        department: "ECE",
        year: "2nd",
        section: "A",
        skills: ["Coordination", "Electronics"],
        interests: ["IoT", "Events"],
        points: 620,
        badges: ["Class Rep", "Boy Rep"],
      },
      {
        id: "u-cr-ece-girl",
        email: "cr.ece.girl@ekc.elevates.live",
        fullName: "Sneha Thomas",
        chapterId: "ch-ekc",
        department: "ECE",
        year: "2nd",
        section: "A",
        skills: ["Coordination", "Design"],
        interests: ["Workshops"],
        points: 600,
        badges: ["Class Rep", "Girl Rep"],
      },
      {
        id: "u-cr-eee",
        email: "cr.eee@ekc.elevates.live",
        fullName: "Meera Krishnan",
        chapterId: "ch-ekc",
        department: "EEE",
        year: "3rd",
        section: "A",
        skills: ["Coordination", "Power systems"],
        interests: ["Workshops"],
        points: 580,
        badges: ["Class Rep", "Girl Rep"],
      },
      {
        id: "u-cr-eee-boy",
        email: "cr.eee.boy@ekc.elevates.live",
        fullName: "Harish Menon",
        chapterId: "ch-ekc",
        department: "EEE",
        year: "3rd",
        section: "A",
        skills: ["Coordination", "Hardware"],
        interests: ["IoT"],
        points: 560,
        badges: ["Class Rep", "Boy Rep"],
      },
      {
        id: "u-student-1",
        email: "ananya@ekc.edu",
        fullName: "Ananya Suresh",
        chapterId: "ch-ekc",
        department: "CSE",
        year: "2nd",
        section: "A",
        skills: ["React", "TypeScript", "UI/UX"],
        interests: ["Web", "Open Source"],
        githubUrl: "https://github.com",
        linkedinUrl: "https://linkedin.com",
        portfolioUrl: "https://ananya.dev",
        points: 540,
        badges: ["First Ship", "Workshop Regular"],
        bio: "Learning in public. Building in clusters.",
        engagementTier: "cluster",
        journeyStage: "projects",
      },
      {
        id: "u-student-2",
        email: "vikram@ekc.edu",
        fullName: "Vikram Das",
        chapterId: "ch-ekc",
        department: "EEE",
        year: "3rd",
        section: "A",
        skills: ["IoT", "Embedded", "Python"],
        interests: ["Hardware", "Automation"],
        points: 410,
        badges: ["Hardware Lab"],
        engagementTier: "active",
        journeyStage: "cluster",
      },
      {
        id: "u-mes-chair",
        email: "chair@mes.elevates.live",
        fullName: "Fathima Zara",
        chapterId: "ch-mes",
        department: "IT",
        year: "4th Year",
        skills: ["Leadership", "Cybersecurity"],
        interests: ["CTF", "Community"],
        points: 990,
        badges: ["Campus Lead"],
        engagementTier: "campus_lead",
        journeyStage: "leadership",
      },
    ],
    roles,
    permissions,
    rolePermissions,
    userRoles: [
      { id: "ur-1", userId: "u-founder", roleId: "r-founder", organizationId: "org-1" },
      { id: "ur-2", userId: "u-hq-admin", roleId: "r-hq-admin", organizationId: "org-1" },
      { id: "ur-3", userId: "u-faculty", roleId: "r-faculty", chapterId: "ch-ekc" },
      { id: "ur-4", userId: "u-chairman", roleId: "r-chairman", chapterId: "ch-ekc", leadershipTermId: "lt-2026" },
      { id: "ur-5", userId: "u-secretary", roleId: "r-sec", chapterId: "ch-ekc", leadershipTermId: "lt-2026" },
      { id: "ur-6", userId: "u-coord", roleId: "r-coord", chapterId: "ch-ekc", leadershipTermId: "lt-2026" },
      { id: "ur-7", userId: "u-cr", roleId: "r-cr", chapterId: "ch-ekc", leadershipTermId: "lt-2026" },
      { id: "ur-7a", userId: "u-cr-cse-boy", roleId: "r-cr", chapterId: "ch-ekc", leadershipTermId: "lt-2026" },
      { id: "ur-7b", userId: "u-cr-ece", roleId: "r-cr", chapterId: "ch-ekc", leadershipTermId: "lt-2026" },
      { id: "ur-7c", userId: "u-cr-ece-girl", roleId: "r-cr", chapterId: "ch-ekc", leadershipTermId: "lt-2026" },
      { id: "ur-7d", userId: "u-cr-eee", roleId: "r-cr", chapterId: "ch-ekc", leadershipTermId: "lt-2026" },
      { id: "ur-7e", userId: "u-cr-eee-boy", roleId: "r-cr", chapterId: "ch-ekc", leadershipTermId: "lt-2026" },
      { id: "ur-8", userId: "u-student-1", roleId: "r-student", chapterId: "ch-ekc" },
      { id: "ur-9", userId: "u-student-2", roleId: "r-student", chapterId: "ch-ekc" },
      { id: "ur-10", userId: "u-mes-chair", roleId: "r-chairman", chapterId: "ch-mes", leadershipTermId: "lt-mes-2026" },
    ],
    departments: [
      { id: "dept-common", chapterId: "ch-ekc", name: "Common" },
      { id: "dept-cse", chapterId: "ch-ekc", name: "CSE" },
      { id: "dept-ece", chapterId: "ch-ekc", name: "ECE" },
      { id: "dept-eee", chapterId: "ch-ekc", name: "EEE" },
    ],
    classCohorts: [
      {
        id: "cc-fy-t1",
        chapterId: "ch-ekc",
        department: "Common",
        year: "1st",
        section: "T1",
        repIds: ["u-cr-cse-boy", "u-cr"],
      },
      {
        id: "cc-fy-t2",
        chapterId: "ch-ekc",
        department: "Common",
        year: "1st",
        section: "T2",
        repIds: ["u-cr-ece", "u-cr-ece-girl"],
      },
      {
        id: "cc-fy-t3",
        chapterId: "ch-ekc",
        department: "Common",
        year: "1st",
        section: "T3",
        // Single-rep example (smaller batch / one CR)
        repIds: ["u-cr-eee-boy"],
      },
      {
        id: "cc-cse-2a",
        chapterId: "ch-ekc",
        department: "CSE",
        year: "2nd",
        section: "A",
        repIds: ["u-cr-cse-boy", "u-cr"],
      },
      {
        id: "cc-ece-2a",
        chapterId: "ch-ekc",
        department: "ECE",
        year: "2nd",
        section: "A",
        repIds: ["u-cr-ece", "u-cr-ece-girl"],
      },
      {
        id: "cc-eee-3a",
        chapterId: "ch-ekc",
        department: "EEE",
        year: "3rd",
        section: "A",
        repIds: ["u-cr-eee-boy", "u-cr-eee"],
      },
    ],
    leadershipTerms: [
      {
        id: "lt-2026",
        chapterId: "ch-ekc",
        academicYear: "2025-26",
        title: "2026 Executive Team",
        startDate: "2025-07-01",
        endDate: "2026-06-30",
        status: "active",
        handoverNotes: "Prioritize cluster roadmaps + public showcase.",
      },
      {
        id: "lt-2025",
        chapterId: "ch-ekc",
        academicYear: "2024-25",
        title: "2025 Executive Team",
        startDate: "2024-07-01",
        endDate: "2025-06-30",
        status: "archived",
        handoverNotes: "Built foundation workshops. Handover clean.",
      },
      {
        id: "lt-mes-2026",
        chapterId: "ch-mes",
        academicYear: "2025-26",
        title: "2026 Executive Team",
        startDate: "2025-07-01",
        endDate: "2026-06-30",
        status: "active",
      },
    ],
    leadershipAssignments: [
      { id: "la-1", termId: "lt-2026", userId: "u-chairman", roleKey: "chairman", title: "Campus Lead" },
      { id: "la-2", termId: "lt-2026", userId: "u-secretary", roleKey: "secretary", title: "Secretary" },
      { id: "la-3", termId: "lt-2026", userId: "u-coord", roleKey: "elevates_coordinator", title: "AI Cluster Coordinator" },
      { id: "la-4", termId: "lt-2026", userId: "u-cr", roleKey: "class_representative", title: "CSE S2 A Girl Representative" },
      { id: "la-4a", termId: "lt-2026", userId: "u-cr-cse-boy", roleKey: "class_representative", title: "CSE S2 A Boy Representative" },
      { id: "la-4b", termId: "lt-2026", userId: "u-cr-ece", roleKey: "class_representative", title: "ECE S2 A Boy Representative" },
      { id: "la-4c", termId: "lt-2026", userId: "u-cr-ece-girl", roleKey: "class_representative", title: "ECE S2 A Girl Representative" },
      { id: "la-4d", termId: "lt-2026", userId: "u-cr-eee", roleKey: "class_representative", title: "EEE S3 A Girl Representative" },
      { id: "la-4e", termId: "lt-2026", userId: "u-cr-eee-boy", roleKey: "class_representative", title: "EEE S3 A Boy Representative" },
      { id: "la-5", termId: "lt-2025", userId: "u-student-2", roleKey: "technical_team", title: "Technical Lead (Alumni term)" },
      { id: "la-mes-1", termId: "lt-mes-2026", userId: "u-mes-chair", roleKey: "chairman", title: "Campus Lead" },
    ],
    events: [
      {
        id: "ev-1",
        chapterId: "ch-ekc",
        clusterId: "cl-web",
        title: "Website Development",
        bannerEmoji: "01",
        description: "Industry workshop — ship a real landing page in one day.",
        venue: "Innovation Lab A",
        startsAt: offsetIso(-3, 9),
        endsAt: offsetIso(-3, 17),
        facultyId: "u-faculty",
        organizerId: "u-secretary",
        capacity: 40,
        waitlistCapacity: 10,
        visibility: "chapter_only",
        registrationStart: offsetIso(-14, 0),
        registrationEnd: offsetIso(-4, 23, 59),
        status: "completed",
        certificateEnabled: true,
        ticketNo: "NO. 06",
        category: "INDUSTRY WORKSHOP",
        progressStage: "workshop",
        nextEventId: "ev-2",
      },
      {
        id: "ev-2",
        chapterId: "ch-ekc",
        clusterId: "cl-iot",
        title: "IoT Hands-On",
        bannerEmoji: "02",
        description: "Hardware chaos. Sensors, microcontrollers, and demos.",
        venue: "Hardware Bay",
        startsAt: offsetIso(2, 10),
        endsAt: offsetIso(2, 16),
        facultyId: "u-faculty",
        organizerId: "u-secretary",
        capacity: 30,
        waitlistCapacity: 8,
        visibility: "all_chapters",
        registrationStart: offsetIso(-10, 0),
        registrationEnd: offsetIso(1, 23, 59),
        status: "registration_open",
        certificateEnabled: true,
        ticketNo: "NO. 07",
        category: "HARDWARE",
        progressStage: "hands_on",
      },
      {
        id: "ev-3",
        chapterId: "ch-ekc",
        clusterId: "cl-ai",
        title: "Build-A-Thon",
        bannerEmoji: "03",
        description: "Useless projects that teach useful skills. Ship weird.",
        venue: "Main Auditorium",
        startsAt: offsetIso(10, 9),
        endsAt: offsetIso(11, 20),
        facultyId: "u-faculty",
        organizerId: "u-coord",
        capacity: 80,
        waitlistCapacity: 20,
        visibility: "public",
        registrationStart: offsetIso(-5, 0),
        registrationEnd: offsetIso(8, 23, 59),
        status: "registration_open",
        certificateEnabled: true,
        ticketNo: "NO. 09",
        category: "USELESS PROJECTS",
        progressStage: "challenge",
      },
      {
        id: "ev-4",
        chapterId: "ch-mes",
        clusterId: "cl-mes-cyber",
        title: "Bug Hunt",
        bannerEmoji: "04",
        description: "Cybersec challenge night.",
        venue: "MES Lab 2",
        startsAt: offsetIso(21, 18),
        endsAt: offsetIso(21, 22),
        organizerId: "u-mes-chair",
        capacity: 50,
        waitlistCapacity: 10,
        visibility: "specific_chapters",
        registrationStart: offsetIso(7, 0),
        registrationEnd: offsetIso(20, 23, 59),
        status: "draft",
        certificateEnabled: true,
        ticketNo: "NO. 11",
        category: "CHALLENGE",
      },
    ],
    eventForms: [
      {
        eventId: "ev-2",
        fields: [
          { id: "f1", key: "name", label: "Name", type: "text", required: true },
          { id: "f2", key: "phone", label: "Phone", type: "tel", required: true },
          {
            id: "f3",
            key: "department",
            label: "Department",
            type: "select",
            required: true,
            options: ["CSE", "ECE", "EEE", "ME", "CE", "Other"],
          },
          {
            id: "f4",
            key: "year",
            label: "Year",
            type: "select",
            required: true,
            options: ["1st", "2nd", "3rd", "4th"],
          },
          {
            id: "f5",
            key: "food",
            label: "Food preference",
            type: "radio",
            required: false,
            options: ["Veg", "Non-veg", "Jain", "None"],
          },
          { id: "f6", key: "laptop", label: "Bringing laptop?", type: "checkbox", required: false },
          { id: "f7", key: "experience", label: "Prior IoT experience", type: "textarea", required: false },
          {
            id: "f8",
            key: "tshirt",
            label: "T-Shirt size",
            type: "select",
            required: false,
            options: ["XS", "S", "M", "L", "XL", "XXL"],
          },
          {
            id: "f9",
            key: "resume",
            label: "Resume",
            type: "resume",
            required: false,
            helpText: "PDF preferred",
          },
          {
            id: "f10",
            key: "emergency_contact",
            label: "Emergency Contact",
            type: "tel",
            required: false,
            placeholder: "+91 …",
          },
          {
            id: "f11",
            key: "email",
            label: "Email",
            type: "email",
            required: true,
          },
        ],
      },
    ],
    forms: [
      {
        id: "form-reg-ev2",
        purpose: "registration",
        title: "IoT Hands-On registration",
        description: "Sign up for the hardware workshop. Bring a laptop if you can.",
        chapterId: "ch-ekc",
        eventId: "ev-2",
        status: "open",
        createdAt: "2026-03-01T09:00:00+05:30",
        updatedAt: "2026-03-10T12:00:00+05:30",
        questions: [
          {
            id: "sec-basics",
            type: "section_header",
            title: "About you",
            description: "Basic details for the roster",
            required: false,
          },
          {
            id: "f-representative",
            type: "representative",
            title: "Class representative",
            description:
              "Choose your class representative (assigned for your class on your profile).",
            required: true,
          },
          { id: "f1", type: "short_text", title: "Full name", required: true },
          { id: "f2", type: "short_text", title: "Phone", required: true },
          { id: "f11", type: "short_text", title: "Email", required: true },
          {
            id: "f3",
            type: "dropdown",
            title: "Department",
            required: true,
            options: ["CSE", "ECE", "EEE", "ME", "CE", "Other"],
          },
          {
            id: "f4",
            type: "dropdown",
            title: "Year",
            required: true,
            options: ["1st", "2nd", "3rd", "4th"],
          },
          {
            id: "sec-prefs",
            type: "section_header",
            title: "Preferences",
            required: false,
          },
          {
            id: "f5",
            type: "multiple_choice",
            title: "Food preference",
            required: false,
            options: ["Veg", "Non-veg", "Jain", "None"],
          },
          {
            id: "f6",
            type: "checkboxes",
            title: "What are you bringing?",
            required: false,
            options: ["Laptop", "Arduino kit", "Nothing"],
          },
          {
            id: "f7",
            type: "paragraph",
            title: "Prior IoT experience",
            required: false,
          },
          {
            id: "f8",
            type: "dropdown",
            title: "T-Shirt size",
            required: false,
            options: ["XS", "S", "M", "L", "XL", "XXL"],
          },
          {
            id: "f-scale",
            type: "linear_scale",
            title: "How excited are you?",
            required: true,
            scaleMin: 1,
            scaleMax: 5,
            scaleMinLabel: "Meh",
            scaleMaxLabel: "Hyped",
          },
          {
            id: "f9",
            type: "file_upload",
            title: "Resume (optional)",
            description: "PDF preferred",
            required: false,
          },
          {
            id: "f10",
            type: "short_text",
            title: "Emergency contact",
            required: false,
          },
        ],
      },
      {
        id: "form-fb-ev1",
        purpose: "feedback",
        title: "Web Dev Workshop feedback",
        description: "Help us improve the next industry workshop.",
        chapterId: "ch-ekc",
        eventId: "ev-1",
        status: "open",
        createdAt: "2026-03-12T18:00:00+05:30",
        updatedAt: "2026-03-13T10:00:00+05:30",
        questions: [
          {
            id: "fb1",
            type: "rating",
            title: "Overall rating",
            required: true,
            ratingMax: 5,
          },
          {
            id: "fb-scale",
            type: "linear_scale",
            title: "How useful was this event?",
            required: true,
            scaleMin: 1,
            scaleMax: 5,
            scaleMinLabel: "Not useful",
            scaleMaxLabel: "Very useful",
          },
          {
            id: "fb2",
            type: "paragraph",
            title: "What did you learn?",
            required: true,
          },
          {
            id: "fb3",
            type: "multiple_choice",
            title: "Would you recommend this event?",
            required: true,
            options: ["Yes", "No", "Maybe"],
          },
          {
            id: "fb4",
            type: "paragraph",
            title: "What should we improve?",
            required: false,
          },
          {
            id: "fb-date",
            type: "date",
            title: "Preferred date for a follow-up session",
            required: false,
          },
        ],
        logicEnabled: true,
        logicRules: [
          {
            id: "logic-fb-improve",
            when: "answer_change",
            if: {
              kind: "answer_equals",
              questionId: "fb3",
              value: "No",
            },
            then: {
              kind: "show_questions",
              questionIds: ["fb4"],
            },
          },
        ],
      },
      {
        id: "form-reg-ev3",
        purpose: "registration",
        title: "Build-A-Thon registration",
        description: "Sign up for Build-A-Thon. Ship something weird.",
        chapterId: "ch-ekc",
        eventId: "ev-3",
        status: "open",
        createdAt: "2026-03-15T09:00:00+05:30",
        updatedAt: "2026-03-18T12:00:00+05:30",
        questions: [
          {
            id: "f-representative",
            type: "representative",
            title: "Class representative",
            description:
              "Choose your class representative (assigned for your class on your profile).",
            required: true,
          },
          { id: "f-name", type: "short_text", title: "Full name", required: true },
          { id: "f-phone", type: "short_text", title: "Phone", required: true },
          { id: "f-dept", type: "short_text", title: "Department", required: true },
          { id: "f-year", type: "short_text", title: "Year", required: true },
          {
            id: "f-idea",
            type: "paragraph",
            title: "What do you want to build?",
            required: false,
          },
        ],
      },
      {
        id: "form-fb-ev3",
        purpose: "feedback",
        title: "Build-A-Thon feedback",
        description: "Tell us how the build went.",
        chapterId: "ch-ekc",
        eventId: "ev-3",
        status: "open",
        createdAt: "2026-03-15T09:00:00+05:30",
        updatedAt: "2026-03-15T09:00:00+05:30",
        questions: [
          {
            id: "fb-rating",
            type: "rating",
            title: "Overall rating",
            required: true,
            ratingMax: 5,
          },
          {
            id: "fb-learned",
            type: "paragraph",
            title: "What did you learn?",
            required: true,
          },
          {
            id: "fb-recommend",
            type: "multiple_choice",
            title: "Would you recommend this event?",
            required: true,
            options: ["Yes", "No", "Maybe"],
          },
        ],
      },
    ],
    formResponses: [
      {
        id: "fres-2",
        formId: "form-fb-ev1",
        userId: "u-student-2",
        eventId: "ev-1",
        answers: {
          fb1: 4,
          "fb-scale": 4,
          fb2: "Responsive layouts and component thinking.",
          fb3: "Yes",
        },
        submittedAt: "2026-03-12T19:00:00+05:30",
      },
      {
        id: "fres-3",
        formId: "form-fb-ev1",
        userId: "u-cr",
        eventId: "ev-1",
        answers: {
          fb1: 4,
          "fb-scale": 3,
          fb2: "Deploy basics and form UX.",
          fb3: "Maybe",
          fb4: "Clearer prerequisites.",
        },
        submittedAt: "2026-03-13T09:15:00+05:30",
      },
      {
        id: "fres-4",
        formId: "form-reg-ev2",
        userId: "u-student-2",
        eventId: "ev-2",
        answers: {
          "f-representative": "u-cr-eee-boy",
          f1: "Rahul Menon",
          f2: "9876501234",
          f11: "rahul@ekc.edu",
          f3: "ECE",
          f4: "3rd",
          f5: "Veg",
          f6: ["Laptop"],
          f7: "Built a weather station last year.",
          "f-scale": 5,
        },
        submittedAt: "2026-03-15T11:00:00+05:30",
      },
    ],
    registrations: [
      {
        id: "reg-1",
        eventId: "ev-1",
        userId: "u-student-1",
        status: "approved",
        representativeId: "u-cr",
        answers: {
          name: "Ananya Suresh",
          department: "CSE",
          year: "2nd",
          laptop: true,
          "f-representative": "u-cr",
        },
        qrCode: "QR-EV1-ANANYA-A1",
        createdAt: "2026-03-01T10:00:00+05:30",
        reviewedBy: "u-cr",
        approvedBy: "u-secretary",
      },
      {
        id: "reg-2",
        eventId: "ev-2",
        userId: "u-student-1",
        status: "approved",
        representativeId: "u-cr-cse-boy",
        answers: {
          name: "Ananya Suresh",
          phone: "9876543210",
          department: "CSE",
          "f-representative": "u-cr-cse-boy",
          year: "2nd",
          food: "Veg",
          laptop: true,
          experience: "Built a DHT11 logger",
          tshirt: "M",
        },
        qrCode: "QR-EV2-ANANYA-A2",
        createdAt: "2026-03-20T12:00:00+05:30",
        reviewedBy: "u-cr",
        approvedBy: "u-secretary",
      },
      {
        id: "reg-3",
        eventId: "ev-2",
        userId: "u-student-2",
        status: "pending",
        representativeId: "u-cr-eee-boy",
        answers: {
          name: "Vikram Das",
          phone: "9876501234",
          department: "EEE",
          year: "3rd",
          food: "Non-veg",
          laptop: false,
          tshirt: "L",
          "f-representative": "u-cr-eee-boy",
        },
        qrCode: "",
        createdAt: "2026-03-21T09:30:00+05:30",
      },
    ],
    attendance: [
      {
        id: "att-1",
        eventId: "ev-1",
        registrationId: "reg-1",
        userId: "u-student-1",
        status: "present",
        method: "qr",
        checkedInAt: "2026-03-12T09:12:00+05:30",
        checkedInBy: "u-cr",
      },
      {
        id: "att-2",
        eventId: "ev-1",
        registrationId: "reg-cr-workshop",
        userId: "u-cr",
        status: "present",
        method: "manual",
        checkedInAt: "2026-03-12T09:20:00+05:30",
        checkedInBy: "u-secretary",
      },
      {
        id: "att-3",
        eventId: "ev-1",
        registrationId: "reg-ece-workshop",
        userId: "u-cr-ece",
        status: "present",
        method: "manual",
        checkedInAt: "2026-03-12T09:25:00+05:30",
        checkedInBy: "u-secretary",
      },
    ],
    certificates: [
      {
        id: "cert-1",
        certificateId: "ELV-EKC-2026-00042",
        eventId: "ev-1",
        userId: "u-student-1",
        issuedAt: "2026-03-12T18:00:00+05:30",
        verificationQr: "VERIFY-ELV-EKC-2026-00042",
        digitalSignature: "sig_elevates_hq_v1_ananya_webdev",
      },
    ],
    clusters: [
      {
        id: "cl-ai",
        chapterId: "ch-ekc",
        name: "AI",
        slug: "ai",
        description: "Models, agents, and applied ML chaos.",
        leaderId: "u-coord",
        facultyId: "u-faculty",
        memberIds: ["u-coord", "u-student-1", "u-chairman"],
        accessMode: "invite",
        challengePrompt: "Ship a tiny notebook that classifies something you care about.",
        responsibilities: [
          "Advanced workshops",
          "Weekly sessions",
          "Open source",
          "Mentorship",
        ],
        roadmap: [
          { week: 1, title: "Python + NumPy warmups", done: true },
          { week: 2, title: "Classic ML pipelines", done: true },
          { week: 3, title: "LLM apps & agents", done: false },
          { week: 4, title: "Demo day mini-projects", done: false },
        ],
      },
      {
        id: "cl-cyber",
        chapterId: "ch-ekc",
        name: "Cybersecurity",
        slug: "cyber",
        description: "Offense, defense, and bug hunts.",
        memberIds: ["u-student-2"],
        accessMode: "challenge",
        challengePrompt: "Write up one finding from a practice CTF box.",
        responsibilities: ["Hackathons", "Weekly sessions", "Mentorship"],
        roadmap: [
          { week: 1, title: "Linux & networking", done: true },
          { week: 2, title: "Web vulns", done: false },
        ],
      },
      {
        id: "cl-web",
        chapterId: "ch-ekc",
        name: "Web",
        slug: "web",
        description: "Frontend, APIs, shipping sites.",
        leaderId: "u-student-1",
        memberIds: ["u-student-1", "u-secretary"],
        accessMode: "invite",
        challengePrompt: "Ship a one-page product landing in a weekend.",
        responsibilities: [
          "Advanced workshops",
          "Internal products",
          "Real client projects",
          "Leadership opportunities",
        ],
        roadmap: [
          { week: 1, title: "HTML/CSS systems", done: true },
          { week: 2, title: "React fundamentals", done: true },
          { week: 3, title: "Ship a product page", done: false },
        ],
      },
      {
        id: "cl-iot",
        chapterId: "ch-ekc",
        name: "IoT",
        slug: "iot",
        description: "Sensors, firmware, and hardware demos.",
        memberIds: ["u-student-2", "u-secretary"],
        roadmap: [{ week: 1, title: "ESP32 basics", done: true }],
      },
      {
        id: "cl-auto",
        chapterId: "ch-ekc",
        name: "Automation",
        slug: "automation",
        description: "n8n, Make, scripts that remove busywork.",
        memberIds: [],
        roadmap: [],
      },
      {
        id: "cl-uiux",
        chapterId: "ch-ekc",
        name: "UI/UX",
        slug: "uiux",
        description: "Interfaces with intentional chaos.",
        memberIds: ["u-cr"],
        roadmap: [],
      },
      {
        id: "cl-media",
        chapterId: "ch-ekc",
        name: "Media",
        slug: "media",
        description: "Posters, reels, brand energy.",
        memberIds: [],
        roadmap: [],
      },
      {
        id: "cl-biz",
        chapterId: "ch-ekc",
        name: "Business",
        slug: "business",
        description: "Sponsorships, startups, pitching.",
        memberIds: ["u-chairman"],
        roadmap: [],
      },
      {
        id: "cl-mes-cyber",
        chapterId: "ch-mes",
        name: "Cybersecurity",
        slug: "cyber",
        description: "MES cyber cluster.",
        leaderId: "u-mes-chair",
        memberIds: ["u-mes-chair"],
        roadmap: [],
      },
    ],
    projects: [
      {
        id: "pr-1",
        chapterId: "ch-ekc",
        clusterId: "cl-web",
        title: "Chapter Public Site",
        description: "Ticket-style event listing + member showcase.",
        stage: "building",
        projectType: "campus",
        teamIds: ["u-student-1", "u-cr"],
        mentorId: "u-faculty",
        repositoryUrl: "https://github.com/elevates/ekc-site",
        progress: 62,
        awards: [],
      },
      {
        id: "pr-2",
        chapterId: "ch-ekc",
        clusterId: "cl-ai",
        title: "Campus FAQ Agent",
        description: "LLM assistant for chapter FAQs and event info.",
        stage: "planning",
        projectType: "internal",
        teamIds: ["u-coord", "u-student-1"],
        mentorId: "u-faculty",
        progress: 25,
        awards: [],
      },
      {
        id: "pr-3",
        chapterId: "ch-ekc",
        clusterId: "cl-iot",
        title: "Lab Occupancy Sensor",
        description: "ESP32 + dashboard for innovation lab occupancy.",
        stage: "demo",
        projectType: "open_source",
        teamIds: ["u-student-2", "u-secretary"],
        progress: 88,
        demoUrl: "https://demo.elevates.live/lab",
        awards: ["Spark Demo Mention"],
      },
    ],
    resourceCategories: [
      { key: "sop", label: "SOP" },
      { key: "workshop_kit", label: "Workshop Kit" },
      { key: "ppt", label: "Presentation" },
      { key: "poster", label: "Poster" },
      { key: "logo", label: "Logo Pack" },
      { key: "certificate", label: "Certificate" },
      { key: "sponsor_deck", label: "Sponsor Deck" },
      { key: "coding", label: "Coding" },
      { key: "recording", label: "Recording" },
    ],
    resources: [
      {
        id: "res-1",
        organizationId: "org-1",
        title: "Event SOP v2",
        category: "sop",
        description: "End-to-end event runbook for chapters.",
        uploadedBy: "u-hq-admin",
        uploadedAt: "2026-01-10T10:00:00+05:30",
        url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      },
      {
        id: "res-2",
        organizationId: "org-1",
        title: "Workshop Kit — Web Crash",
        category: "workshop_kit",
        description: "Slides, starter repo, checklist.",
        uploadedBy: "u-founder",
        uploadedAt: "2026-02-01T10:00:00+05:30",
        url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      },
      {
        id: "res-3",
        organizationId: "org-1",
        title: "Elevates Logo Pack",
        category: "logo",
        description: "Official SVG wordmark + mark for chapters.",
        uploadedBy: "u-hq-admin",
        uploadedAt: "2025-12-01T10:00:00+05:30",
        url: "/elevates-mark.svg",
      },
      {
        id: "res-3b",
        organizationId: "org-1",
        title: "Event Poster Template",
        category: "poster",
        description: "Chapter event poster layout — headline, date, CTA.",
        uploadedBy: "u-hq-admin",
        uploadedAt: "2026-01-05T10:00:00+05:30",
        url: "/elevates-poster.svg",
      },
      {
        id: "res-4",
        organizationId: "org-1",
        title: "Certificate Template",
        category: "certificate",
        description: "Print + digital certificate master.",
        uploadedBy: "u-hq-admin",
        uploadedAt: "2026-01-20T10:00:00+05:30",
        url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      },
      {
        id: "res-5",
        organizationId: "org-1",
        title: "Sponsor Deck 2026",
        category: "sponsor_deck",
        description: "Partnership one-pager + deck.",
        uploadedBy: "u-founder",
        uploadedAt: "2026-02-15T10:00:00+05:30",
        url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
      },
    ],
    guidelines: [
      {
        id: "pol-1",
        organizationId: "org-1",
        title: "Chapter Onboarding SOP",
        category: "Operations",
        version: "v2.1",
        summary:
          "Launch a chapter student-led — Campus Lead + exec team, optional faculty liaison, first open workshop.",
        sections: [
          "Student-led launch",
          "Optional faculty liaison",
          "Executive roster",
          "Cluster setup",
          "First workshop",
        ],
        body: `Elevates chapters launch student-led. A Campus Lead recruits an executive roster (Chairman, Secretary, Coordinators) before the first public event.

Faculty coordinators are optional liaisons — they advise and unblock campus logistics, but do not replace student ownership of calendar, budget asks, or member culture.

Before opening registration for the first workshop, confirm: executive roles assigned in Elevates OS, at least one cluster or track named, and a venue or online room booked. Publish an announcement with date, capacity, and what attendees will build.`,
        status: "published",
        updatedBy: "u-hq-admin",
        updatedAt: "2026-01-12T10:00:00+05:30",
      },
      {
        id: "pol-2",
        organizationId: "org-1",
        title: "Event Approval Workflow",
        category: "Events",
        version: "v3.1",
        summary:
          "Draft → Exec publish (faculty optional) → Registration open → Attendance → Report → Certificate.",
        sections: [
          "Faculty optional liaison",
          "Capacity limits",
          "Cross-chapter visibility rules",
        ],
        body: `Events move Draft → Registration open → Completed. Executive roles may publish without faculty sign-off; faculty remain optional reviewers for campus-sensitive dates or venues.

Set capacity before opening registration. Waitlists are allowed; do not overbook rooms. Cross-chapter visibility (all_chapters / specific_chapters) requires HQ awareness for flagship programs.

After the event: close registration, run attendance (QR or manual), submit an event report within 72 hours, then issue certificates only for eligible attendees.`,
        status: "published",
        updatedBy: "u-hq-admin",
        updatedAt: "2026-02-01T10:00:00+05:30",
      },
      {
        id: "pol-3",
        organizationId: "org-1",
        title: "Registration & Attendance Policy",
        category: "Members",
        version: "v1.4",
        summary:
          "Two-step registration: Representative review, then Secretary approval. QR check-in at venue.",
        sections: [
          "CR review queue",
          "Secretary approval",
          "Waitlist handling",
          "Certificate eligibility",
        ],
        body: `Registration is two-step by default: Class Representative review, then Secretary approval. Rejected applicants receive a short reason in the app.

Waitlisted members promote in order when capacity frees. Manual overrides are logged.

Attendance uses QR check-in at the venue (or manual mark for speakers/volunteers). Certificate eligibility requires approved registration and a present/late attendance record unless HQ grants an exception.`,
        status: "published",
        updatedBy: "u-hq-admin",
        updatedAt: "2026-01-28T10:00:00+05:30",
      },
      {
        id: "pol-4",
        organizationId: "org-1",
        title: "Leadership Handover Guide",
        category: "Governance",
        version: "v1.0",
        summary:
          "End-of-term checklist — document handover notes, transfer permissions, archive reports.",
        sections: [
          "Handover notes field",
          "Role reassignment",
          "Audit trail",
        ],
        body: `At term end, outgoing leads complete handover notes covering open tasks, vendor contacts, unfinished reports, and cluster health.

HQ or chapter admins reassign leadership roles in Elevates OS before the new term start date. Archive completed terms; do not delete historical assignments.

Activity logs remain the source of truth for who changed roles and when.`,
        status: "published",
        updatedBy: "u-founder",
        updatedAt: "2025-12-15T10:00:00+05:30",
      },
      {
        id: "pol-5",
        organizationId: "org-1",
        title: "Brand & Communications",
        category: "Brand",
        version: "v2.0",
        summary:
          "Use official logo pack. Poster templates in resource library. No unauthorized sponsor claims.",
        sections: [
          "Logo usage",
          "Social media templates",
          "Sponsor deck approval",
        ],
        body: `Chapters must use the official Elevates mark and color kit from the Brand page. Do not stretch, recolor, or add drop shadows to the logo.

Poster and social templates live in the Resource library. Sponsor claims and partnership decks require HQ review before public posting.

See the Brand kit for copyable colors, usage rules, and downloads.`,
        status: "published",
        relatedHref: "/hq/brand",
        updatedBy: "u-hq-admin",
        updatedAt: "2026-01-20T10:00:00+05:30",
      },
      {
        id: "pol-6",
        organizationId: "org-1",
        title: "Report Submission Standards",
        category: "Reporting",
        version: "v1.2",
        summary:
          "Monthly reports due by 5th. Event reports within 72 hours. HQ review with comments.",
        sections: [
          "Report types",
          "Submission deadlines",
          "HQ approval flow",
        ],
        body: `Monthly chapter reports are due by the 5th of the following month. Event reports are due within 72 hours of event end.

Reports should include outcomes, attendance summary, issues, and next steps. Attach photos or links where helpful.

HQ reviews with Approve, Request correction, or Reject. Chapters revise when changes are requested and resubmit promptly.`,
        status: "published",
        updatedBy: "u-hq-admin",
        updatedAt: "2026-02-10T10:00:00+05:30",
      },
    ],
    tasks: [
      {
        id: "task-1",
        chapterId: "ch-ekc",
        eventId: "ev-2",
        title: "Confirm Hardware Bay booking",
        category: "venue",
        assigneeId: "u-secretary",
        status: "completed",
        dueDate: "2026-04-01",
      },
      {
        id: "task-2",
        chapterId: "ch-ekc",
        eventId: "ev-2",
        title: "Poster + Instagram carousel",
        category: "marketing",
        assigneeId: "u-cr",
        status: "in_progress",
        dueDate: "2026-04-05",
      },
      {
        id: "task-3",
        chapterId: "ch-ekc",
        eventId: "ev-2",
        title: "Open registration form",
        category: "registration",
        assigneeId: "u-cr",
        status: "completed",
        dueDate: "2026-03-01",
      },
      {
        id: "task-4",
        chapterId: "ch-ekc",
        eventId: "ev-3",
        title: "Certificate batch for Build-A-Thon",
        category: "certificates",
        assigneeId: "u-secretary",
        status: "pending",
        dueDate: "2026-05-12",
      },
      {
        id: "task-5",
        chapterId: "ch-ekc",
        title: "March activity report draft",
        category: "documentation",
        assigneeId: "u-secretary",
        status: "in_progress",
        dueDate: "2026-04-05",
      },
    ],
    reports: [
      {
        id: "rep-1",
        chapterId: "ch-ekc",
        type: "event",
        title: "Website Development — Event Report",
        summary:
          "48 students registered, 41 attended. Built a chapter landing page in 4 hours. Faculty noted strong collaboration between CSE and ECE batches.",
        bodyHtml: `<h1>Website Development — Event Report</h1>
<p><strong>Chapter:</strong> EKC Elevates · <strong>Date:</strong> 15 Mar 2026 · <strong>Venue:</strong> Lab Block A</p>
<h2>Summary</h2>
<p>48 students registered, 41 attended. Teams shipped a chapter landing page in a 4-hour build sprint. Faculty noted strong CSE–ECE collaboration.</p>
<h2>Highlights</h2>
<ul><li>Landing page live on chapter resources</li><li>6 first-time builders completed a PR</li><li>Photo wall + demo circle at closing</li></ul>
<h2>Next steps</h2>
<p>Reuse the same format for the IoT Hands-On weekend. CR roster cleanup for EEE remains open.</p>
<p><em>Prepared by Diya Nair · Elevates OS</em></p>`,
        source: "manual",
        images: [],
        status: "approved",
        submittedBy: "u-secretary",
        submittedAt: "2026-03-15T12:00:00+05:30",
        hqComment: "Excellent turnout. Reuse format for IoT.",
        approvedBy: "u-hq-admin",
        updatedAt: "2026-03-16T10:00:00+05:30",
        updatedBy: "u-hq-admin",
      },
      {
        id: "rep-2",
        chapterId: "ch-ekc",
        type: "monthly",
        title: "March 2026 Monthly Report",
        summary:
          "Two public events, AI cluster week 3 completed, health score steady. Pending: Build-A-Thon venue confirmation and CR roster cleanup for EEE.",
        bodyHtml: `<h1>March 2026 Monthly Report</h1>
<p><strong>Chapter:</strong> EKC Elevates</p>
<h2>Summary</h2>
<p>Two public events shipped, AI cluster week 3 completed, health score steady. Pending Build-A-Thon venue confirmation and CR roster cleanup for EEE.</p>
<h2>Programs</h2>
<ul><li>Website Development workshop — completed</li><li>IoT Hands-On — registration open</li><li>AI cluster — week 3 FAQ agent scaffold</li></ul>
<h2>Asks for HQ</h2>
<p>Confirm mentor slot for Build-A-Thon and share brand pack for college submission pack.</p>
<p><em>Prepared by Arjun Menon · Elevates OS</em></p>`,
        source: "manual",
        images: [],
        status: "submitted",
        submittedBy: "u-chairman",
        submittedAt: "2026-04-02T18:00:00+05:30",
        updatedAt: "2026-04-02T18:00:00+05:30",
        updatedBy: "u-chairman",
      },
      {
        id: "rep-3",
        chapterId: "ch-mes",
        type: "activity",
        title: "MES Q1 Activity Report",
        summary:
          "Draft: orientation meetup + first mentor circle. Numbers and photos still being collected before HQ submit.",
        bodyHtml: `<h1>MES Q1 Activity Report</h1>
<p><em>Draft</em> — orientation meetup + first mentor circle. Numbers and photos still being collected.</p>
<h2>Planned sections</h2>
<ul><li>Attendance</li><li>Photos</li><li>Outcomes</li></ul>`,
        source: "manual",
        images: [],
        status: "draft",
        submittedBy: "u-mes-chair",
        updatedAt: "2026-03-28T12:00:00+05:30",
        updatedBy: "u-mes-chair",
      },
      {
        id: "rep-4",
        chapterId: "ch-ekc",
        type: "event",
        eventId: "ev-1",
        title: "Website Development — Activity Report",
        summary:
          "Student auto-draft from event photos and outcomes — ready to polish before submit.",
        bodyHtml: `<h1>Website Development — Activity Report</h1>
<p><strong>Chapter:</strong> EKC Elevates · <strong>Venue:</strong> Lab Block A</p>
<h2>Summary</h2>
<p>We ran a hands-on build where students shipped a chapter landing page. Great energy from first-years; mentors unblocked CSS layout issues live.</p>
<h2>Participation</h2>
<p>Registrations and attendance pulled from Elevates OS event records.</p>
<h2>Outcomes</h2>
<p>Three teams demoed; two pages are reusable for the next workshop.</p>
<p><em>Prepared by Ananya Krishnan · Elevates OS</em></p>`,
        source: "student_auto",
        images: [],
        status: "draft",
        submittedBy: "u-student-1",
        updatedAt: "2026-03-16T15:00:00+05:30",
        updatedBy: "u-student-1",
      },
    ],
    announcements: [
      {
        id: "an-1",
        audience: "global",
        title: "Leadership Cycle 2026 is live",
        body: "All chapters: update executive rosters and handover notes before April 30.",
        authorId: "u-founder",
        createdAt: "2026-03-01T09:00:00+05:30",
      },
      {
        id: "an-2",
        audience: "chapter",
        chapterId: "ch-ekc",
        title: "IoT Hands-On registration open",
        body: "Representatives: verify class lists. Capacity 30 + waitlist 8.",
        authorId: "u-secretary",
        createdAt: "2026-03-18T11:00:00+05:30",
      },
      {
        id: "an-3",
        audience: "cluster",
        chapterId: "ch-ekc",
        clusterId: "cl-ai",
        title: "AI cluster week 3 starts Monday",
        body: "Bring laptops. We'll scaffold an agent that answers Elevates FAQs.",
        authorId: "u-coord",
        createdAt: "2026-03-25T16:00:00+05:30",
      },
      {
        id: "an-4",
        audience: "executive",
        chapterId: "ch-ekc",
        title: "Exec sync Friday 5PM",
        body: "Agenda: Build-A-Thon faculty approval + health score review.",
        authorId: "u-chairman",
        createdAt: "2026-03-26T10:00:00+05:30",
      },
    ],
    outboundMessages: [],
    notifications: [
      {
        id: "n-hq-1",
        userId: "u-hq-admin",
        title: "Report awaiting HQ review",
        body: "EKC March monthly report is ready for review.",
        read: false,
        createdAt: "2026-04-02T18:10:00+05:30",
        href: "/hq/reports",
      },
      {
        id: "n-hq-2",
        userId: "u-founder",
        title: "Chapter onboarding needs attention",
        body: "Review chapter health and onboarding notes across the network.",
        read: false,
        createdAt: "2026-04-01T11:00:00+05:30",
        href: "/hq/chapters",
      },
      {
        id: "n-hq-3",
        userId: "u-hq-admin",
        title: "Network broadcast ready",
        body: "Publish a global announcement from HQ Alerts when you have network news.",
        read: false,
        createdAt: "2026-03-28T09:30:00+05:30",
        href: "/hq/notifications",
      },
      {
        id: "n-1",
        userId: "u-chairman",
        title: "Report awaiting HQ review",
        body: "March monthly report submitted. Track status on chapter reports.",
        read: false,
        createdAt: "2026-04-02T18:05:00+05:30",
        href: "/chapter/ekc/reports",
      },
      {
        id: "n-2",
        userId: "u-secretary",
        title: "2 registrations need approval",
        body: "IoT Hands-On queue.",
        read: false,
        createdAt: "2026-03-21T10:00:00+05:30",
        href: "/chapter/ekc/events",
      },
      {
        id: "n-3",
        userId: "u-faculty",
        title: "Build-A-Thon is live",
        body: "Registration is open — monitor attendance and chapter health from Faculty.",
        read: false,
        createdAt: "2026-03-22T09:00:00+05:30",
        href: "/chapter/ekc/events/ev-3",
      },
      {
        id: "n-4",
        userId: "u-student-1",
        title: "Certificate ready",
        body: "Website Development certificate issued.",
        read: true,
        createdAt: "2026-03-12T18:01:00+05:30",
        href: "/profile/u-student-1",
      },
    ],
    activityLogs: [
      {
        id: "log-1",
        actorId: "u-secretary",
        action: "event_created",
        entity: "event",
        entityId: "ev-3",
        createdAt: "2026-03-20T14:00:00+05:30",
        meta: "Build-A-Thon",
      },
      {
        id: "log-2",
        actorId: "u-secretary",
        action: "event_updated",
        entity: "event",
        entityId: "ev-3",
        createdAt: "2026-03-20T14:30:00+05:30",
        meta: "Build-A-Thon",
      },
      {
        id: "log-3",
        actorId: "u-cr",
        action: "registration_reviewed",
        entity: "registration",
        entityId: "reg-2",
        createdAt: "2026-03-20T15:00:00+05:30",
        meta: "IoT Hands-On",
      },
      {
        id: "log-4",
        actorId: "u-secretary",
        action: "registration_approved",
        entity: "registration",
        entityId: "reg-2",
        createdAt: "2026-03-20T16:00:00+05:30",
        meta: "IoT Hands-On",
      },
      {
        id: "log-5",
        actorId: "u-cr",
        action: "check_in",
        entity: "attendance",
        entityId: "reg-1",
        createdAt: "2026-03-12T10:15:00+05:30",
        meta: "Website Development Workshop",
      },
      {
        id: "log-6",
        actorId: "u-chairman",
        action: "report_submitted",
        entity: "report",
        entityId: "rep-2",
        createdAt: "2026-04-02T18:00:00+05:30",
        meta: "March monthly report",
      },
      {
        id: "log-7",
        actorId: "u-hq-admin",
        action: "report_approved",
        entity: "report",
        entityId: "rep-1",
        createdAt: "2026-03-16T11:00:00+05:30",
        meta: "Website Development Workshop report",
      },
      {
        id: "log-8",
        actorId: "u-founder",
        action: "resource_uploaded",
        entity: "resource",
        entityId: "res-5",
        createdAt: "2026-02-15T10:00:00+05:30",
        meta: "Sponsor Deck 2026",
      },
      {
        id: "log-9",
        actorId: "u-hq-admin",
        action: "guideline_created",
        entity: "guideline",
        entityId: "pol-1",
        createdAt: "2026-01-12T10:00:00+05:30",
        meta: "Chapter Onboarding SOP",
      },
      {
        id: "log-10",
        actorId: "u-founder",
        action: "announcement_published",
        entity: "announcement",
        entityId: "an-1",
        createdAt: "2026-03-01T09:00:00+05:30",
        meta: "Leadership Cycle 2026 is live",
      },
      {
        id: "log-11",
        actorId: "u-hq-admin",
        action: "brand_kit_updated",
        entity: "organization",
        entityId: "org-1",
        createdAt: "2026-01-20T10:05:00+05:30",
        meta: "Elevates HQ",
      },
      {
        id: "log-12",
        actorId: "u-hq-admin",
        action: "chapter_updated",
        entity: "chapter",
        entityId: "ch-ekc",
        createdAt: "2026-02-28T12:00:00+05:30",
        meta: "EKC Chapter",
      },
    ],

    clusterInvites: [
      {
        id: "ci-1",
        clusterId: "cl-web",
        chapterId: "ch-ekc",
        userId: "u-student-2",
        nominatedBy: "u-cr",
        status: "pending",
        note: "Strong IoT → curious about web. Talent discovery pick.",
        createdAt: "2026-04-01T10:00:00+05:30",
      },
    ],
    leadershipApplications: [
      {
        id: "la-app-1",
        termId: "lt-2026",
        chapterId: "ch-ekc",
        userId: "u-student-1",
        roleKey: "elevates_coordinator",
        title: "AI Cluster Coordinator",
        status: "screening",
        statement: "I have been shipping in Web + AI clusters and want to mentor juniors.",
        createdAt: "2026-03-01T10:00:00+05:30",
        updatedAt: "2026-03-05T10:00:00+05:30",
      },
    ],
    chapterStandardChecks: [
      { id: "csc-1", chapterId: "ch-ekc", standardId: "workshops", done: true, updatedAt: "2026-03-01T10:00:00+05:30" },
      { id: "csc-2", chapterId: "ch-ekc", standardId: "clusters", done: true, updatedAt: "2026-03-01T10:00:00+05:30" },
      { id: "csc-3", chapterId: "ch-ekc", standardId: "projects", done: true, updatedAt: "2026-03-01T10:00:00+05:30" },
      { id: "csc-4", chapterId: "ch-ekc", standardId: "docs", done: false, updatedAt: "2026-03-01T10:00:00+05:30" },
      { id: "csc-5", chapterId: "ch-ekc", standardId: "feedback", done: true, updatedAt: "2026-03-01T10:00:00+05:30" },
      { id: "csc-6", chapterId: "ch-ekc", standardId: "outcomes", done: false, updatedAt: "2026-03-01T10:00:00+05:30" },
      { id: "csc-7", chapterId: "ch-ekc", standardId: "juniors", done: true, updatedAt: "2026-03-01T10:00:00+05:30" },
    ],
    session: {
      userId: "u-chairman",
      roleKey: "chairman",
      chapterId: "ch-ekc",
    },
  };
}
