import type {
  ElevatesStore,
  Permission,
  PermissionKey,
  Role,
  RoleKey,
} from "@/types";

const roles: Role[] = [
  { id: "r-founder", key: "founder", name: "Founder", scope: "hq", description: "Full HQ authority" },
  { id: "r-hq-admin", key: "hq_admin", name: "HQ Admin", scope: "hq", description: "Organization operations" },
  { id: "r-hq-mentor", key: "hq_mentor", name: "HQ Mentor", scope: "hq", description: "Cross-chapter mentorship" },
  { id: "r-faculty", key: "faculty_coordinator", name: "Faculty Coordinator", scope: "chapter", description: "Faculty oversight" },
  { id: "r-chairman", key: "chairman", name: "Chairman", scope: "chapter", description: "Chapter executive lead" },
  { id: "r-vc", key: "vice_chairman", name: "Vice Chairman", scope: "chapter", description: "Deputy executive" },
  { id: "r-sec", key: "secretary", name: "Secretary", scope: "chapter", description: "Events & operations" },
  { id: "r-js", key: "joint_secretary", name: "Joint Secretary", scope: "chapter", description: "Supports secretary" },
  { id: "r-coord", key: "elevates_coordinator", name: "Elevates Coordinator", scope: "chapter", description: "Cluster & program coord" },
  { id: "r-tech", key: "technical_team", name: "Technical Team", scope: "chapter", description: "Tech delivery" },
  { id: "r-media", key: "media_team", name: "Media Team", scope: "chapter", description: "Design & media" },
  { id: "r-cr", key: "class_representative", name: "Class Representative", scope: "chapter", description: "Class registrations & attendance" },
  { id: "r-student", key: "student", name: "Student", scope: "chapter", description: "Member" },
  { id: "r-alumni", key: "alumni", name: "Alumni", scope: "chapter", description: "Past member" },
  { id: "r-guest", key: "guest", name: "Guest", scope: "chapter", description: "External guest" },
  { id: "r-mentor", key: "industry_mentor", name: "Industry Mentor", scope: "chapter", description: "Industry guidance" },
];

const permissionDefs: { key: PermissionKey; name: string; description: string }[] = [
  { key: "org.manage", name: "Manage Organization", description: "Full HQ control" },
  { key: "chapter.create", name: "Create Chapter", description: "Spin up new chapters" },
  { key: "chapter.manage", name: "Manage Chapter", description: "Edit chapter settings" },
  { key: "leadership.manage", name: "Manage Leadership", description: "Leadership cycles" },
  { key: "roles.manage", name: "Manage Roles", description: "Assign roles & permissions" },
  { key: "event.create", name: "Create Event", description: "Draft & publish events" },
  { key: "event.approve", name: "Approve Event", description: "Faculty/HQ event approval" },
  { key: "event.manage", name: "Manage Event", description: "Edit event details" },
  { key: "registration.review", name: "Review Registrations", description: "Representative review" },
  { key: "registration.approve", name: "Approve Registrations", description: "Secretary approval" },
  { key: "attendance.verify", name: "Verify Attendance", description: "Check-in students" },
  { key: "certificate.issue", name: "Issue Certificates", description: "Generate certificates" },
  { key: "report.submit", name: "Submit Reports", description: "Chapter reports" },
  { key: "report.approve", name: "Approve Reports", description: "HQ report approval" },
  { key: "task.manage", name: "Manage Tasks", description: "Assign & track tasks" },
  { key: "resource.upload", name: "Upload Resources", description: "Library uploads" },
  { key: "announcement.publish", name: "Publish Announcements", description: "Broadcast messages" },
  { key: "analytics.view", name: "View Analytics", description: "Dashboards & scores" },
  { key: "student.register", name: "Register Students", description: "CR registration rights" },
];

const permissions: Permission[] = permissionDefs.map((p, i) => ({
  id: `p-${i + 1}`,
  ...p,
}));

const allPermIds = permissions.map((p) => p.id);
const permByKey = Object.fromEntries(permissions.map((p) => [p.key, p.id])) as Record<
  PermissionKey,
  string
>;

function allow(keys: PermissionKey[]) {
  return keys.map((k) => permByKey[k]);
}

const roleAllow: Record<RoleKey, PermissionKey[]> = {
  founder: permissionDefs.map((p) => p.key),
  hq_admin: permissionDefs.map((p) => p.key),
  hq_mentor: ["analytics.view", "report.approve", "announcement.publish"],
  faculty_coordinator: [
    "event.approve",
    "report.submit",
    "analytics.view",
    "announcement.publish",
    "chapter.manage",
  ],
  chairman: [
    "chapter.manage",
    "leadership.manage",
    "event.create",
    "event.manage",
    "event.approve",
    "registration.approve",
    "attendance.verify",
    "certificate.issue",
    "report.submit",
    "task.manage",
    "announcement.publish",
    "analytics.view",
    "roles.manage",
  ],
  vice_chairman: [
    "chapter.manage",
    "event.create",
    "event.manage",
    "registration.approve",
    "task.manage",
    "report.submit",
    "analytics.view",
    "announcement.publish",
  ],
  secretary: [
    "event.create",
    "event.manage",
    "registration.approve",
    "attendance.verify",
    "certificate.issue",
    "task.manage",
    "report.submit",
    "announcement.publish",
    "analytics.view",
  ],
  joint_secretary: [
    "event.manage",
    "registration.review",
    "attendance.verify",
    "task.manage",
    "announcement.publish",
  ],
  elevates_coordinator: [
    "event.manage",
    "registration.review",
    "attendance.verify",
    "task.manage",
    "announcement.publish",
    "analytics.view",
  ],
  technical_team: ["event.manage", "task.manage", "attendance.verify"],
  media_team: ["event.manage", "task.manage", "announcement.publish"],
  class_representative: [
    "student.register",
    "registration.review",
    "attendance.verify",
    "announcement.publish",
  ],
  student: [],
  alumni: [],
  guest: [],
  industry_mentor: ["analytics.view", "announcement.publish"],
};

const rolePermissions = roles.flatMap((role) => {
  const allowed = new Set(allow(roleAllow[role.key]));
  return allPermIds.map((permissionId) => ({
    roleId: role.id,
    permissionId,
    allowed: allowed.has(permissionId),
  }));
});

export function createSeedStore(): ElevatesStore {
  return {
    organization: {
      id: "org-1",
      name: "Elevates HQ",
      slug: "elevates",
      tagline: "Learn. Build. Grow. Ship. Repeat.",
    },
    chapters: [
      {
        id: "ch-ekc",
        organizationId: "org-1",
        name: "EKC Chapter",
        slug: "ekc",
        college: "Eranad Knowledge City",
        city: "Manjeri",
        status: "active",
        healthScore: 94,
        memberCount: 186,
        eventCount: 13,
        projectCount: 8,
        foundedAt: "2024-08-01",
        facultyId: "u-faculty",
        notes: "Flagship chapter. Prioritize Build-A-Thon and cluster demos.",
      },
      {
        id: "ch-mes",
        organizationId: "org-1",
        name: "MES Chapter",
        slug: "mes",
        college: "MES College of Engineering",
        city: "Kuttippuram",
        status: "active",
        healthScore: 87,
        memberCount: 142,
        eventCount: 9,
        projectCount: 5,
        foundedAt: "2025-01-15",
      },
      {
        id: "ch-cusat",
        organizationId: "org-1",
        name: "CUSAT Chapter",
        slug: "cusat",
        college: "Cochin University of Science and Technology",
        city: "Kochi",
        status: "onboarding",
        healthScore: 72,
        memberCount: 64,
        eventCount: 3,
        projectCount: 2,
        foundedAt: "2025-11-01",
      },
    ],
    profiles: [
      {
        id: "u-founder",
        email: "founder@elevates.live",
        fullName: "Sarhan Qadir",
        department: "HQ",
        skills: ["Strategy", "Community", "Product"],
        interests: ["Open Source", "Education"],
        githubUrl: "https://github.com",
        linkedinUrl: "https://linkedin.com",
        points: 2400,
        badges: ["Founder", "Ship Captain"],
        bio: "Building the OS for student innovation communities.",
      },
      {
        id: "u-hq-admin",
        email: "admin@elevates.live",
        fullName: "Aisha Rahman",
        department: "HQ Ops",
        skills: ["Ops", "Analytics"],
        interests: ["Systems"],
        points: 1200,
        badges: ["HQ Admin"],
      },
      {
        id: "u-faculty",
        email: "faculty@ekc.edu",
        fullName: "Dr. Meera Nair",
        chapterId: "ch-ekc",
        department: "CSE",
        skills: ["Mentorship", "Research"],
        interests: ["AI", "Education"],
        points: 900,
        badges: ["Faculty"],
      },
      {
        id: "u-chairman",
        email: "chairman@ekc.elevates.live",
        fullName: "Arjun Menon",
        chapterId: "ch-ekc",
        department: "CSE",
        year: "4th Year",
        skills: ["Leadership", "Full Stack", "Public Speaking"],
        interests: ["Hackathons", "Startups"],
        githubUrl: "https://github.com",
        linkedinUrl: "https://linkedin.com",
        portfolioUrl: "https://elevates.live",
        points: 1880,
        badges: ["Chairman 2026", "Builder", "Top 1%"],
        bio: "Midnight coder. Chapter lead. Ships chaos into products.",
      },
      {
        id: "u-secretary",
        email: "secretary@ekc.elevates.live",
        fullName: "Diya Krishnan",
        chapterId: "ch-ekc",
        department: "ECE",
        year: "3rd Year",
        skills: ["Operations", "Event Design", "IoT"],
        interests: ["Hardware", "Community"],
        points: 1420,
        badges: ["Secretary", "Ops Ace"],
      },
      {
        id: "u-coord",
        email: "coord@ekc.elevates.live",
        fullName: "Rahul Dev",
        chapterId: "ch-ekc",
        department: "CSE",
        year: "3rd Year",
        skills: ["AI", "Python", "Workshops"],
        interests: ["ML", "Clusters"],
        points: 1100,
        badges: ["Coordinator"],
      },
      {
        id: "u-cr",
        email: "cr@ekc.elevates.live",
        fullName: "Naina Fathima",
        chapterId: "ch-ekc",
        department: "CSE",
        year: "2nd Year",
        skills: ["Coordination", "Design"],
        interests: ["UI/UX"],
        points: 760,
        badges: ["Class Rep"],
      },
      {
        id: "u-student-1",
        email: "ananya@ekc.edu",
        fullName: "Ananya Suresh",
        chapterId: "ch-ekc",
        department: "CSE",
        year: "2nd Year",
        skills: ["React", "TypeScript", "UI/UX"],
        interests: ["Web", "Open Source"],
        githubUrl: "https://github.com",
        linkedinUrl: "https://linkedin.com",
        portfolioUrl: "https://ananya.dev",
        points: 540,
        badges: ["First Ship", "Workshop Regular"],
        bio: "Learning in public. Building in clusters.",
      },
      {
        id: "u-student-2",
        email: "vikram@ekc.edu",
        fullName: "Vikram Das",
        chapterId: "ch-ekc",
        department: "EEE",
        year: "3rd Year",
        skills: ["IoT", "Embedded", "Python"],
        interests: ["Hardware", "Automation"],
        points: 410,
        badges: ["Hardware Lab"],
      },
      {
        id: "u-mes-chair",
        email: "chair@mes.elevates.live",
        fullName: "Fathima Zara",
        chapterId: "ch-mes",
        department: "IT",
        year: "4th Year",
        skills: ["Leadership", "Cybersecurity"],
        interests: ["CTF", "Community"],
        points: 990,
        badges: ["Chairman"],
      },
    ],
    roles,
    permissions,
    rolePermissions,
    userRoles: [
      { id: "ur-1", userId: "u-founder", roleId: "r-founder", organizationId: "org-1" },
      { id: "ur-2", userId: "u-hq-admin", roleId: "r-hq-admin", organizationId: "org-1" },
      { id: "ur-3", userId: "u-faculty", roleId: "r-faculty", chapterId: "ch-ekc" },
      { id: "ur-4", userId: "u-chairman", roleId: "r-chairman", chapterId: "ch-ekc", leadershipTermId: "lt-2026" },
      { id: "ur-5", userId: "u-secretary", roleId: "r-sec", chapterId: "ch-ekc", leadershipTermId: "lt-2026" },
      { id: "ur-6", userId: "u-coord", roleId: "r-coord", chapterId: "ch-ekc", leadershipTermId: "lt-2026" },
      { id: "ur-7", userId: "u-cr", roleId: "r-cr", chapterId: "ch-ekc", leadershipTermId: "lt-2026" },
      { id: "ur-8", userId: "u-student-1", roleId: "r-student", chapterId: "ch-ekc" },
      { id: "ur-9", userId: "u-student-2", roleId: "r-student", chapterId: "ch-ekc" },
      { id: "ur-10", userId: "u-mes-chair", roleId: "r-chairman", chapterId: "ch-mes", leadershipTermId: "lt-mes-2026" },
    ],
    leadershipTerms: [
      {
        id: "lt-2026",
        chapterId: "ch-ekc",
        academicYear: "2025-26",
        title: "2026 Executive Team",
        startDate: "2025-07-01",
        endDate: "2026-06-30",
        status: "active",
        handoverNotes: "Prioritize cluster roadmaps + public showcase.",
      },
      {
        id: "lt-2025",
        chapterId: "ch-ekc",
        academicYear: "2024-25",
        title: "2025 Executive Team",
        startDate: "2024-07-01",
        endDate: "2025-06-30",
        status: "archived",
        handoverNotes: "Built foundation workshops. Handover clean.",
      },
      {
        id: "lt-mes-2026",
        chapterId: "ch-mes",
        academicYear: "2025-26",
        title: "2026 Executive Team",
        startDate: "2025-07-01",
        endDate: "2026-06-30",
        status: "active",
      },
    ],
    leadershipAssignments: [
      { id: "la-1", termId: "lt-2026", userId: "u-chairman", roleKey: "chairman", title: "Chairman" },
      { id: "la-2", termId: "lt-2026", userId: "u-secretary", roleKey: "secretary", title: "Secretary" },
      { id: "la-3", termId: "lt-2026", userId: "u-coord", roleKey: "elevates_coordinator", title: "AI Cluster Coordinator" },
      { id: "la-4", termId: "lt-2026", userId: "u-cr", roleKey: "class_representative", title: "CSE S2 Representative" },
      { id: "la-5", termId: "lt-2025", userId: "u-student-2", roleKey: "technical_team", title: "Technical Lead (Alumni term)" },
    ],
    events: [
      {
        id: "ev-1",
        chapterId: "ch-ekc",
        clusterId: "cl-web",
        title: "Website Development",
        bannerEmoji: "01",
        description: "Industry workshop — ship a real landing page in one day.",
        venue: "Innovation Lab A",
        startsAt: "2026-03-12T09:00:00+05:30",
        endsAt: "2026-03-12T17:00:00+05:30",
        facultyId: "u-faculty",
        organizerId: "u-secretary",
        capacity: 40,
        waitlistCapacity: 10,
        visibility: "chapter_only",
        registrationStart: "2026-02-20T00:00:00+05:30",
        registrationEnd: "2026-03-10T23:59:00+05:30",
        status: "completed",
        certificateEnabled: true,
        ticketNo: "NO. 06",
        category: "INDUSTRY WORKSHOP",
      },
      {
        id: "ev-2",
        chapterId: "ch-ekc",
        clusterId: "cl-iot",
        title: "IoT Hands-On",
        bannerEmoji: "02",
        description: "Hardware chaos. Sensors, microcontrollers, and demos.",
        venue: "Hardware Bay",
        startsAt: "2026-04-18T10:00:00+05:30",
        endsAt: "2026-04-18T16:00:00+05:30",
        facultyId: "u-faculty",
        organizerId: "u-secretary",
        capacity: 30,
        waitlistCapacity: 8,
        visibility: "all_chapters",
        registrationStart: "2026-03-01T00:00:00+05:30",
        registrationEnd: "2026-04-15T23:59:00+05:30",
        status: "registration_open",
        certificateEnabled: true,
        ticketNo: "NO. 07",
        category: "HARDWARE",
      },
      {
        id: "ev-3",
        chapterId: "ch-ekc",
        clusterId: "cl-ai",
        title: "Build-A-Thon",
        bannerEmoji: "03",
        description: "Useless projects that teach useful skills. Ship weird.",
        venue: "Main Auditorium",
        startsAt: "2026-05-09T09:00:00+05:30",
        endsAt: "2026-05-10T20:00:00+05:30",
        facultyId: "u-faculty",
        organizerId: "u-coord",
        capacity: 80,
        waitlistCapacity: 20,
        visibility: "public",
        registrationStart: "2026-04-01T00:00:00+05:30",
        registrationEnd: "2026-05-05T23:59:00+05:30",
        status: "pending_approval",
        certificateEnabled: true,
        ticketNo: "NO. 09",
        category: "USELESS PROJECTS",
      },
      {
        id: "ev-4",
        chapterId: "ch-mes",
        clusterId: "cl-mes-cyber",
        title: "Bug Hunt",
        bannerEmoji: "04",
        description: "Cybersec challenge night.",
        venue: "MES Lab 2",
        startsAt: "2026-04-25T18:00:00+05:30",
        endsAt: "2026-04-25T22:00:00+05:30",
        organizerId: "u-mes-chair",
        capacity: 50,
        waitlistCapacity: 10,
        visibility: "specific_chapters",
        registrationStart: "2026-04-01T00:00:00+05:30",
        registrationEnd: "2026-04-23T23:59:00+05:30",
        status: "approved",
        certificateEnabled: true,
        ticketNo: "NO. 11",
        category: "CHALLENGE",
      },
    ],
    eventForms: [
      {
        eventId: "ev-2",
        fields: [
          { id: "f1", key: "name", label: "Name", type: "text", required: true },
          { id: "f2", key: "phone", label: "Phone", type: "tel", required: true },
          {
            id: "f3",
            key: "department",
            label: "Department",
            type: "select",
            required: true,
            options: ["CSE", "ECE", "EEE", "ME", "CE", "Other"],
          },
          {
            id: "f4",
            key: "year",
            label: "Year",
            type: "select",
            required: true,
            options: ["1st", "2nd", "3rd", "4th"],
          },
          {
            id: "f5",
            key: "food",
            label: "Food preference",
            type: "radio",
            required: false,
            options: ["Veg", "Non-veg", "Jain", "None"],
          },
          { id: "f6", key: "laptop", label: "Bringing laptop?", type: "checkbox", required: false },
          { id: "f7", key: "experience", label: "Prior IoT experience", type: "textarea", required: false },
          {
            id: "f8",
            key: "tshirt",
            label: "T-Shirt size",
            type: "select",
            required: false,
            options: ["XS", "S", "M", "L", "XL", "XXL"],
          },
          {
            id: "f9",
            key: "resume",
            label: "Resume",
            type: "resume",
            required: false,
            helpText: "PDF preferred",
          },
          {
            id: "f10",
            key: "emergency_contact",
            label: "Emergency Contact",
            type: "tel",
            required: false,
            placeholder: "+91 …",
          },
          {
            id: "f11",
            key: "email",
            label: "Email",
            type: "email",
            required: true,
          },
        ],
      },
    ],
    forms: [
      {
        id: "form-reg-ev2",
        purpose: "registration",
        title: "IoT Hands-On registration",
        description: "Sign up for the hardware workshop. Bring a laptop if you can.",
        chapterId: "ch-ekc",
        eventId: "ev-2",
        status: "open",
        createdAt: "2026-03-01T09:00:00+05:30",
        updatedAt: "2026-03-10T12:00:00+05:30",
        questions: [
          {
            id: "sec-basics",
            type: "section_header",
            title: "About you",
            description: "Basic details for the roster",
            required: false,
          },
          { id: "f1", type: "short_text", title: "Full name", required: true },
          { id: "f2", type: "short_text", title: "Phone", required: true },
          { id: "f11", type: "short_text", title: "Email", required: true },
          {
            id: "f3",
            type: "dropdown",
            title: "Department",
            required: true,
            options: ["CSE", "ECE", "EEE", "ME", "CE", "Other"],
          },
          {
            id: "f4",
            type: "dropdown",
            title: "Year",
            required: true,
            options: ["1st", "2nd", "3rd", "4th"],
          },
          {
            id: "sec-prefs",
            type: "section_header",
            title: "Preferences",
            required: false,
          },
          {
            id: "f5",
            type: "multiple_choice",
            title: "Food preference",
            required: false,
            options: ["Veg", "Non-veg", "Jain", "None"],
          },
          {
            id: "f6",
            type: "checkboxes",
            title: "What are you bringing?",
            required: false,
            options: ["Laptop", "Arduino kit", "Nothing"],
          },
          {
            id: "f7",
            type: "paragraph",
            title: "Prior IoT experience",
            required: false,
          },
          {
            id: "f8",
            type: "dropdown",
            title: "T-Shirt size",
            required: false,
            options: ["XS", "S", "M", "L", "XL", "XXL"],
          },
          {
            id: "f-scale",
            type: "linear_scale",
            title: "How excited are you?",
            required: true,
            scaleMin: 1,
            scaleMax: 5,
            scaleMinLabel: "Meh",
            scaleMaxLabel: "Hyped",
          },
          {
            id: "f9",
            type: "file_upload",
            title: "Resume (optional)",
            description: "PDF preferred",
            required: false,
          },
          {
            id: "f10",
            type: "short_text",
            title: "Emergency contact",
            required: false,
          },
        ],
      },
      {
        id: "form-fb-ev1",
        purpose: "feedback",
        title: "Web Dev Workshop feedback",
        description: "Help us improve the next industry workshop.",
        chapterId: "ch-ekc",
        eventId: "ev-1",
        status: "open",
        createdAt: "2026-03-12T18:00:00+05:30",
        updatedAt: "2026-03-13T10:00:00+05:30",
        questions: [
          {
            id: "fb1",
            type: "rating",
            title: "Overall rating",
            required: true,
            ratingMax: 5,
          },
          {
            id: "fb-scale",
            type: "linear_scale",
            title: "How useful was this event?",
            required: true,
            scaleMin: 1,
            scaleMax: 5,
            scaleMinLabel: "Not useful",
            scaleMaxLabel: "Very useful",
          },
          {
            id: "fb2",
            type: "paragraph",
            title: "What did you learn?",
            required: true,
          },
          {
            id: "fb3",
            type: "multiple_choice",
            title: "Would you recommend this event?",
            required: true,
            options: ["Yes", "No", "Maybe"],
          },
          {
            id: "fb4",
            type: "paragraph",
            title: "What should we improve?",
            required: false,
          },
          {
            id: "fb-date",
            type: "date",
            title: "Preferred date for a follow-up session",
            required: false,
          },
        ],
      },
    ],
    formResponses: [
      {
        id: "fres-1",
        formId: "form-fb-ev1",
        userId: "u-student-1",
        eventId: "ev-1",
        answers: {
          fb1: 5,
          "fb-scale": 5,
          fb2: "How to structure a landing page and ship CSS tokens.",
          fb3: "Yes",
          fb4: "More time for the build lab.",
        },
        submittedAt: "2026-03-12T18:30:00+05:30",
      },
      {
        id: "fres-2",
        formId: "form-fb-ev1",
        userId: "u-student-2",
        eventId: "ev-1",
        answers: {
          fb1: 4,
          "fb-scale": 4,
          fb2: "Responsive layouts and component thinking.",
          fb3: "Yes",
        },
        submittedAt: "2026-03-12T19:00:00+05:30",
      },
      {
        id: "fres-3",
        formId: "form-fb-ev1",
        userId: "u-cr",
        eventId: "ev-1",
        answers: {
          fb1: 4,
          "fb-scale": 3,
          fb2: "Deploy basics and form UX.",
          fb3: "Maybe",
          fb4: "Clearer prerequisites.",
        },
        submittedAt: "2026-03-13T09:15:00+05:30",
      },
      {
        id: "fres-4",
        formId: "form-reg-ev2",
        userId: "u-student-2",
        eventId: "ev-2",
        answers: {
          f1: "Rahul Menon",
          f2: "9876501234",
          f11: "rahul@ekc.edu",
          f3: "ECE",
          f4: "3rd",
          f5: "Veg",
          f6: ["Laptop"],
          f7: "Built a weather station last year.",
          "f-scale": 5,
        },
        submittedAt: "2026-03-15T11:00:00+05:30",
      },
    ],
    registrations: [
      {
        id: "reg-1",
        eventId: "ev-1",
        userId: "u-student-1",
        status: "approved",
        answers: { name: "Ananya Suresh", department: "CSE", year: "2nd", laptop: true },
        qrCode: "QR-EV1-ANANYA-A1",
        createdAt: "2026-03-01T10:00:00+05:30",
        reviewedBy: "u-cr",
        approvedBy: "u-secretary",
      },
      {
        id: "reg-2",
        eventId: "ev-2",
        userId: "u-student-1",
        status: "approved",
        answers: {
          name: "Ananya Suresh",
          phone: "9876543210",
          department: "CSE",
          year: "2nd",
          food: "Veg",
          laptop: true,
          experience: "Built a DHT11 logger",
          tshirt: "M",
        },
        qrCode: "QR-EV2-ANANYA-A2",
        createdAt: "2026-03-20T12:00:00+05:30",
        reviewedBy: "u-cr",
        approvedBy: "u-secretary",
      },
      {
        id: "reg-3",
        eventId: "ev-2",
        userId: "u-student-2",
        status: "pending",
        answers: {
          name: "Vikram Das",
          phone: "9876501234",
          department: "EEE",
          year: "3rd",
          food: "Non-veg",
          laptop: false,
          tshirt: "L",
        },
        qrCode: "",
        createdAt: "2026-03-21T09:30:00+05:30",
      },
    ],
    attendance: [
      {
        id: "att-1",
        eventId: "ev-1",
        registrationId: "reg-1",
        userId: "u-student-1",
        status: "present",
        method: "qr",
        checkedInAt: "2026-03-12T09:12:00+05:30",
        checkedInBy: "u-cr",
      },
    ],
    certificates: [
      {
        id: "cert-1",
        certificateId: "ELV-EKC-2026-00042",
        eventId: "ev-1",
        userId: "u-student-1",
        issuedAt: "2026-03-12T18:00:00+05:30",
        verificationQr: "VERIFY-ELV-EKC-2026-00042",
        digitalSignature: "sig_elevates_hq_v1_ananya_webdev",
      },
    ],
    clusters: [
      {
        id: "cl-ai",
        chapterId: "ch-ekc",
        name: "AI",
        slug: "ai",
        description: "Models, agents, and applied ML chaos.",
        leaderId: "u-coord",
        facultyId: "u-faculty",
        memberIds: ["u-coord", "u-student-1", "u-chairman"],
        roadmap: [
          { week: 1, title: "Python + NumPy warmups", done: true },
          { week: 2, title: "Classic ML pipelines", done: true },
          { week: 3, title: "LLM apps & agents", done: false },
          { week: 4, title: "Demo day mini-projects", done: false },
        ],
      },
      {
        id: "cl-cyber",
        chapterId: "ch-ekc",
        name: "Cybersecurity",
        slug: "cyber",
        description: "Offense, defense, and bug hunts.",
        memberIds: ["u-student-2"],
        roadmap: [
          { week: 1, title: "Linux & networking", done: true },
          { week: 2, title: "Web vulns", done: false },
        ],
      },
      {
        id: "cl-web",
        chapterId: "ch-ekc",
        name: "Web",
        slug: "web",
        description: "Frontend, APIs, shipping sites.",
        leaderId: "u-student-1",
        memberIds: ["u-student-1", "u-secretary"],
        roadmap: [
          { week: 1, title: "HTML/CSS systems", done: true },
          { week: 2, title: "React fundamentals", done: true },
          { week: 3, title: "Ship a product page", done: false },
        ],
      },
      {
        id: "cl-iot",
        chapterId: "ch-ekc",
        name: "IoT",
        slug: "iot",
        description: "Sensors, firmware, and hardware demos.",
        memberIds: ["u-student-2", "u-secretary"],
        roadmap: [{ week: 1, title: "ESP32 basics", done: true }],
      },
      {
        id: "cl-auto",
        chapterId: "ch-ekc",
        name: "Automation",
        slug: "automation",
        description: "n8n, Make, scripts that remove busywork.",
        memberIds: [],
        roadmap: [],
      },
      {
        id: "cl-uiux",
        chapterId: "ch-ekc",
        name: "UI/UX",
        slug: "uiux",
        description: "Interfaces with intentional chaos.",
        memberIds: ["u-cr"],
        roadmap: [],
      },
      {
        id: "cl-media",
        chapterId: "ch-ekc",
        name: "Media",
        slug: "media",
        description: "Posters, reels, brand energy.",
        memberIds: [],
        roadmap: [],
      },
      {
        id: "cl-biz",
        chapterId: "ch-ekc",
        name: "Business",
        slug: "business",
        description: "Sponsorships, startups, pitching.",
        memberIds: ["u-chairman"],
        roadmap: [],
      },
      {
        id: "cl-mes-cyber",
        chapterId: "ch-mes",
        name: "Cybersecurity",
        slug: "cyber",
        description: "MES cyber cluster.",
        leaderId: "u-mes-chair",
        memberIds: ["u-mes-chair"],
        roadmap: [],
      },
    ],
    projects: [
      {
        id: "pr-1",
        chapterId: "ch-ekc",
        clusterId: "cl-web",
        title: "Chapter Public Site",
        description: "Ticket-style event listing + member showcase.",
        stage: "building",
        teamIds: ["u-student-1", "u-cr"],
        mentorId: "u-faculty",
        repositoryUrl: "https://github.com/elevates/ekc-site",
        progress: 62,
        awards: [],
      },
      {
        id: "pr-2",
        chapterId: "ch-ekc",
        clusterId: "cl-ai",
        title: "Campus FAQ Agent",
        description: "LLM assistant for chapter FAQs and event info.",
        stage: "planning",
        teamIds: ["u-coord", "u-student-1"],
        mentorId: "u-faculty",
        progress: 25,
        awards: [],
      },
      {
        id: "pr-3",
        chapterId: "ch-ekc",
        clusterId: "cl-iot",
        title: "Lab Occupancy Sensor",
        description: "ESP32 + dashboard for innovation lab occupancy.",
        stage: "demo",
        teamIds: ["u-student-2", "u-secretary"],
        progress: 88,
        demoUrl: "https://demo.elevates.live/lab",
        awards: ["Spark Demo Mention"],
      },
    ],
    resources: [
      {
        id: "res-1",
        organizationId: "org-1",
        title: "Event SOP v2",
        category: "sop",
        description: "End-to-end event runbook for chapters.",
        uploadedBy: "u-hq-admin",
        uploadedAt: "2026-01-10T10:00:00+05:30",
        url: "#",
      },
      {
        id: "res-2",
        organizationId: "org-1",
        title: "Workshop Kit — Web Crash",
        category: "workshop_kit",
        description: "Slides, starter repo, checklist.",
        uploadedBy: "u-founder",
        uploadedAt: "2026-02-01T10:00:00+05:30",
        url: "#",
      },
      {
        id: "res-3",
        organizationId: "org-1",
        title: "Elevates Logo Pack",
        category: "logo",
        description: "SVG/PNG brand assets.",
        uploadedBy: "u-hq-admin",
        uploadedAt: "2025-12-01T10:00:00+05:30",
        url: "#",
      },
      {
        id: "res-4",
        organizationId: "org-1",
        title: "Certificate Template",
        category: "certificate",
        description: "Print + digital certificate master.",
        uploadedBy: "u-hq-admin",
        uploadedAt: "2026-01-20T10:00:00+05:30",
        url: "#",
      },
      {
        id: "res-5",
        organizationId: "org-1",
        title: "Sponsor Deck 2026",
        category: "sponsor_deck",
        description: "Partnership one-pager + deck.",
        uploadedBy: "u-founder",
        uploadedAt: "2026-02-15T10:00:00+05:30",
        url: "#",
      },
    ],
    tasks: [
      {
        id: "task-1",
        chapterId: "ch-ekc",
        eventId: "ev-2",
        title: "Confirm Hardware Bay booking",
        category: "venue",
        assigneeId: "u-secretary",
        status: "completed",
        dueDate: "2026-04-01",
      },
      {
        id: "task-2",
        chapterId: "ch-ekc",
        eventId: "ev-2",
        title: "Poster + Instagram carousel",
        category: "marketing",
        assigneeId: "u-cr",
        status: "in_progress",
        dueDate: "2026-04-05",
      },
      {
        id: "task-3",
        chapterId: "ch-ekc",
        eventId: "ev-2",
        title: "Open registration form",
        category: "registration",
        assigneeId: "u-cr",
        status: "completed",
        dueDate: "2026-03-01",
      },
      {
        id: "task-4",
        chapterId: "ch-ekc",
        eventId: "ev-3",
        title: "Certificate batch for Build-A-Thon",
        category: "certificates",
        assigneeId: "u-secretary",
        status: "pending",
        dueDate: "2026-05-12",
      },
      {
        id: "task-5",
        chapterId: "ch-ekc",
        title: "March activity report draft",
        category: "documentation",
        assigneeId: "u-secretary",
        status: "in_progress",
        dueDate: "2026-04-05",
      },
    ],
    reports: [
      {
        id: "rep-1",
        chapterId: "ch-ekc",
        type: "event",
        title: "Website Development — Event Report",
        status: "approved",
        submittedBy: "u-secretary",
        submittedAt: "2026-03-15T12:00:00+05:30",
        hqComment: "Excellent turnout. Reuse format for IoT.",
        approvedBy: "u-hq-admin",
      },
      {
        id: "rep-2",
        chapterId: "ch-ekc",
        type: "monthly",
        title: "March 2026 Monthly Report",
        status: "submitted",
        submittedBy: "u-chairman",
        submittedAt: "2026-04-02T18:00:00+05:30",
      },
      {
        id: "rep-3",
        chapterId: "ch-mes",
        type: "activity",
        title: "MES Q1 Activity Report",
        status: "draft",
        submittedBy: "u-mes-chair",
      },
    ],
    announcements: [
      {
        id: "an-1",
        audience: "global",
        title: "Leadership Cycle 2026 is live",
        body: "All chapters: update executive rosters and handover notes before April 30.",
        authorId: "u-founder",
        createdAt: "2026-03-01T09:00:00+05:30",
      },
      {
        id: "an-2",
        audience: "chapter",
        chapterId: "ch-ekc",
        title: "IoT Hands-On registration open",
        body: "Representatives: verify class lists. Capacity 30 + waitlist 8.",
        authorId: "u-secretary",
        createdAt: "2026-03-18T11:00:00+05:30",
      },
      {
        id: "an-3",
        audience: "cluster",
        chapterId: "ch-ekc",
        clusterId: "cl-ai",
        title: "AI cluster week 3 starts Monday",
        body: "Bring laptops. We'll scaffold an agent that answers Elevates FAQs.",
        authorId: "u-coord",
        createdAt: "2026-03-25T16:00:00+05:30",
      },
      {
        id: "an-4",
        audience: "executive",
        chapterId: "ch-ekc",
        title: "Exec sync Friday 5PM",
        body: "Agenda: Build-A-Thon faculty approval + health score review.",
        authorId: "u-chairman",
        createdAt: "2026-03-26T10:00:00+05:30",
      },
    ],
    notifications: [
      {
        id: "n-1",
        userId: "u-chairman",
        title: "Report awaiting HQ review",
        body: "March monthly report submitted.",
        read: false,
        createdAt: "2026-04-02T18:05:00+05:30",
        href: "/hq/reports",
      },
      {
        id: "n-2",
        userId: "u-secretary",
        title: "2 registrations need approval",
        body: "IoT Hands-On queue.",
        read: false,
        createdAt: "2026-03-21T10:00:00+05:30",
        href: "/chapter/ekc/events",
      },
      {
        id: "n-3",
        userId: "u-faculty",
        title: "Event pending approval",
        body: "Build-A-Thon needs faculty sign-off.",
        read: false,
        createdAt: "2026-03-22T09:00:00+05:30",
        href: "/faculty",
      },
      {
        id: "n-4",
        userId: "u-student-1",
        title: "Certificate ready",
        body: "Website Development certificate issued.",
        read: true,
        createdAt: "2026-03-12T18:01:00+05:30",
        href: "/profile/u-student-1",
      },
    ],
    activityLogs: [
      {
        id: "log-1",
        actorId: "u-secretary",
        action: "created_event",
        entity: "event",
        entityId: "ev-3",
        createdAt: "2026-03-20T14:00:00+05:30",
        meta: "Build-A-Thon",
      },
      {
        id: "log-2",
        actorId: "u-cr",
        action: "reviewed_registration",
        entity: "registration",
        entityId: "reg-2",
        createdAt: "2026-03-20T15:00:00+05:30",
      },
      {
        id: "log-3",
        actorId: "u-hq-admin",
        action: "approved_report",
        entity: "report",
        entityId: "rep-1",
        createdAt: "2026-03-16T11:00:00+05:30",
      },
      {
        id: "log-4",
        actorId: "u-founder",
        action: "uploaded_resource",
        entity: "resource",
        entityId: "res-5",
        createdAt: "2026-02-15T10:00:00+05:30",
      },
    ],
    session: {
      userId: "u-chairman",
      roleKey: "chairman",
      chapterId: "ch-ekc",
    },
  };
}
