import { offsetIso } from "@/lib/datetime";
import type {
  Certificate,
  Chapter,
  ElevatesStore,
  EventItem,
  Permission,
  PermissionKey,
  Profile,
  Report,
  Role,
  RoleKey,
} from "@/types";

const roles: Role[] = [
  { id: "r-founder", key: "founder", name: "Founder", scope: "hq", description: "Full HQ authority" },
  { id: "r-hq-admin", key: "hq_admin", name: "HQ Admin", scope: "hq", description: "Organization operations" },
  { id: "r-faculty", key: "faculty_coordinator", name: "Faculty Coordinator", scope: "chapter", description: "Faculty oversight" },
  { id: "r-chairman", key: "chairman", name: "Chairman (Campus Lead)", scope: "chapter", description: "Campus Chapter Lead & Executive Head" },
  { id: "r-vc", key: "vice_chairman", name: "Vice Chairman", scope: "chapter", description: "Deputy Campus Lead" },
  { id: "r-sec", key: "secretary", name: "Secretary", scope: "chapter", description: "Events & operations" },
  { id: "r-jsec", key: "joint_secretary", name: "Joint Secretary", scope: "chapter", description: "Event operations & support" },
  { id: "r-tech-lead", key: "technical_lead", name: "Technical Team Head", scope: "chapter", description: "Technical lead (2 Heads)" },
  { id: "r-tech-team", key: "technical_team", name: "Technical Team Member", scope: "chapter", description: "Technical development member" },
  { id: "r-media-lead", key: "media_lead", name: "Media Team Head", scope: "chapter", description: "Media lead (2 Heads)" },
  { id: "r-media-team", key: "media_team", name: "Media Team Member", scope: "chapter", description: "Media team member (8 Members)" },
  { id: "r-inno-lead", key: "innovation_lead", name: "Innovation Team Head", scope: "chapter", description: "Innovation lead (2 Heads)" },
  { id: "r-inno-team", key: "innovation_team", name: "Innovation Team Member", scope: "chapter", description: "Innovation lab member" },
  { id: "r-coord", key: "elevates_coordinator", name: "Elevates Coordinator", scope: "chapter", description: "Cluster & program coordinator" },
  { id: "r-cr", key: "class_representative", name: "Class Representative", scope: "chapter", description: "Class representative" },
  { id: "r-student", key: "student", name: "Student", scope: "chapter", description: "Student member" },
];

const permissionDefs: { key: PermissionKey; name: string; description: string }[] = [
  { key: "org.manage", name: "Manage Organization", description: "Full HQ control" },
  { key: "chapter.create", name: "Create Chapter", description: "Spin up new chapters" },
  { key: "chapter.manage", name: "Manage Chapter", description: "Edit chapter settings" },
  { key: "leadership.manage", name: "Manage Leadership", description: "Leadership cycles" },
  { key: "class.manage", name: "Manage Classes", description: "Class divisions and representatives" },
  { key: "roles.manage", name: "Manage Roles", description: "Assign roles & permissions" },
  { key: "event.create", name: "Create Event", description: "Draft & publish events" },
  { key: "event.approve", name: "Approve Event", description: "Faculty/HQ event approval" },
  { key: "event.manage", name: "Manage Event", description: "Edit event details" },
  { key: "registration.review", name: "Review Registrations", description: "Representative review" },
  { key: "registration.approve", name: "Approve Registrations", description: "Secretary approval" },
  { key: "attendance.verify", name: "Verify Attendance", description: "Check-in students" },
  { key: "certificate.issue", name: "Issue Certificates", description: "Generate certificates" },
  { key: "report.submit", name: "Submit Reports", description: "Chapter reports" },
  { key: "report.approve", name: "Approve Reports", description: "HQ report approval" },
  { key: "report.download", name: "Download Reports", description: "Download approved reports as documents" },
  { key: "task.manage", name: "Manage Tasks", description: "Assign & track tasks" },
  { key: "resource.upload", name: "Upload Resources", description: "Library uploads" },
  { key: "announcement.publish", name: "Publish Announcements", description: "Broadcast messages" },
  { key: "analytics.view", name: "View Analytics", description: "Dashboards & scores" },
  { key: "student.register", name: "Register Students", description: "CR registration rights" },
];

const permissions: Permission[] = permissionDefs.map((p, i) => ({
  id: `p-${i + 1}`,
  ...p,
}));

const allPermIds = permissions.map((p) => p.id);
const permByKey = Object.fromEntries(permissions.map((p) => [p.key, p.id])) as Record<
  PermissionKey,
  string
>;

function allow(keys: PermissionKey[]) {
  return keys.map((k) => permByKey[k]);
}

const roleAllow: Record<RoleKey, PermissionKey[]> = {
  founder: permissionDefs.map((p) => p.key),
  hq_admin: permissionDefs.map((p) => p.key),
  hq_mentor: ["analytics.view", "report.approve", "announcement.publish"],
  faculty_coordinator: [
    "event.approve",
    "report.submit",
    "report.download",
    "analytics.view",
    "announcement.publish",
    "chapter.manage",
  ],
  chairman: [
    "chapter.manage",
    "leadership.manage",
    "class.manage",
    "event.create",
    "event.manage",
    "event.approve",
    "registration.review",
    "registration.approve",
    "attendance.verify",
    "certificate.issue",
    "report.submit",
    "report.download",
    "task.manage",
    "announcement.publish",
    "analytics.view",
    "roles.manage",
  ],
  vice_chairman: [
    "chapter.manage",
    "class.manage",
    "event.create",
    "event.manage",
    "registration.review",
    "attendance.verify",
    "task.manage",
    "announcement.publish",
  ],
  secretary: [
    "class.manage",
    "event.create",
    "event.manage",
    "registration.approve",
    "attendance.verify",
    "certificate.issue",
    "task.manage",
    "report.submit",
    "report.download",
    "announcement.publish",
    "analytics.view",
  ],
  joint_secretary: [
    "event.create",
    "event.manage",
    "registration.review",
    "attendance.verify",
    "task.manage",
    "announcement.publish",
  ],
  elevates_coordinator: [
    "class.manage",
    "event.create",
    "event.manage",
    "registration.review",
    "attendance.verify",
    "task.manage",
    "announcement.publish",
    "analytics.view",
  ],
  technical_lead: [
    "event.create",
    "event.manage",
    "task.manage",
    "attendance.verify",
    "announcement.publish",
    "analytics.view",
  ],
  technical_team: ["event.manage", "task.manage", "attendance.verify"],
  media_lead: [
    "event.manage",
    "task.manage",
    "announcement.publish",
    "analytics.view",
  ],
  media_team: ["event.manage", "task.manage", "announcement.publish"],
  innovation_lead: [
    "event.create",
    "event.manage",
    "task.manage",
    "announcement.publish",
    "analytics.view",
  ],
  innovation_team: ["event.manage", "task.manage"],
  class_representative: [
    "student.register",
    "registration.review",
    "attendance.verify",
    "announcement.publish",
    "report.submit",
    "report.download",
  ],
  student: ["report.submit", "report.download"],
  alumni: [],
  guest: [],
  industry_mentor: ["analytics.view", "announcement.publish"],
};

const rolePermissions = roles.flatMap((role) => {
  const allowed = new Set(allow(roleAllow[role.key] ?? []));
  return allPermIds.map((permissionId) => ({
    roleId: role.id,
    permissionId,
    allowed: allowed.has(permissionId),
  }));
});

// ── ALL 18 CANONICAL FOUNDERS FROM src/data/team/founders.ts ────────────────
const defaultProfiles: Profile[] = [
  {
    id: "usr-sarhan",
    fullName: "Sarhan Qadir KVM",
    email: "sarhan@elevates.live",
    avatarUrl: "/images/founders/sarhan-qadir.jpeg",
    department: "Computer Science & Engineering",
    year: "4th Year",
    section: "A",
    chapterId: "ch-ekc",
    status: "active",
    isPublic: true,
    skills: ["Full-Stack", "Next.js", "PostgreSQL", "System Architecture"],
    interests: ["High-Load Systems", "Community Building"],
    points: 2500,
    badges: ["Founder", "Core Builder", "Platform Lead"],
    bio: "Founder & Full-stack builder. Architected Vibranium, Aaroh, and Elevates platform.",
  },
  {
    id: "usr-naseem",
    fullName: "Naseem Shan",
    email: "naseem@elevates.live",
    avatarUrl: "/images/founders/naseem-shan.jpeg",
    department: "Computer Science & Engineering",
    year: "4th Year",
    section: "A",
    chapterId: "ch-ekc",
    status: "active",
    isPublic: true,
    skills: ["Backend", "Systems", "Infrastructure"],
    interests: ["Distributed Systems", "Cloud"],
    points: 2100,
    badges: ["Founder", "Backend Lead"],
    bio: "Founder · Backend Systems & Infrastructure Lead.",
  },
  {
    id: "usr-nafih",
    fullName: "Muhammed Nafih P",
    email: "nafih@elevates.live",
    avatarUrl: "/images/founders/nafih.jpeg",
    department: "Computer Science & Engineering",
    year: "4th Year",
    section: "A",
    chapterId: "ch-ekc",
    status: "active",
    isPublic: true,
    skills: ["UI/UX", "Figma", "Branding", "Visual Design"],
    interests: ["Design Systems", "Brand Architecture"],
    points: 1900,
    badges: ["Founder", "Design Lead"],
    bio: "Founder · Design & Creative Director.",
  },
  {
    id: "usr-anildas",
    fullName: "Anil Das P",
    email: "anildas@elevates.live",
    avatarUrl: "/images/founders/anil-das.jpeg",
    department: "Computer Science & Engineering",
    year: "4th Year",
    section: "B",
    chapterId: "ch-ekc",
    status: "active",
    isPublic: true,
    skills: ["Full-Stack", "React", "Node.js"],
    interests: ["Rapid Prototyping", "Hackathons"],
    points: 1800,
    badges: ["Founder", "Core Engineer"],
    bio: "Founder · Full-Stack Engineer.",
  },
  {
    id: "usr-nadheem",
    fullName: "Nadheem Roshan",
    email: "nadheem@elevates.live",
    avatarUrl: "/images/founders/nadheem.jpg",
    department: "Cyber Security",
    year: "4th Year",
    section: "A",
    chapterId: "ch-ekc",
    status: "active",
    isPublic: true,
    skills: ["IoT", "Hardware", "Embedded Systems", "Robotics"],
    interests: ["Hardware Hacking", "Microcontrollers"],
    points: 1750,
    badges: ["Founder", "IoT Lead"],
    bio: "Founder · IoT & Hardware Lead.",
  },
  {
    id: "usr-adhinan",
    fullName: "Adhinan K",
    email: "adhinan@elevates.live",
    avatarUrl: "/images/founders/adhinan.png",
    department: "Cyber Security",
    year: "4th Year",
    section: "A",
    chapterId: "ch-ekc",
    status: "active",
    isPublic: true,
    skills: ["Ethical Hacking", "Kali Linux", "CTF", "Network Defense"],
    interests: ["Reverse Engineering", "AppSec"],
    points: 2200,
    badges: ["Founder", "CyberSec Lead", "CTF Champion"],
    bio: "Founder · Cybersecurity Researcher & Defense Lead.",
  },
  {
    id: "usr-mashood",
    fullName: "Mashood M",
    email: "mashood@elevates.live",
    avatarUrl: "/images/founders/mashood.jpeg",
    department: "Computer Science & Business Systems",
    year: "4th Year",
    section: "A",
    chapterId: "ch-ekc",
    status: "active",
    isPublic: true,
    skills: ["AI Engineering", "LLM Reasoning", "Data Science"],
    interests: ["Autonomous Agents", "Prompt Engineering"],
    points: 1950,
    badges: ["Founder", "AI Lead"],
    bio: "Founder · AI & Data Science Lead.",
  },
  {
    id: "usr-adil",
    fullName: "Adil",
    email: "adil@elevates.live",
    avatarUrl: "/images/founders/adil.jpeg",
    department: "Computer Science & Engineering",
    year: "4th Year",
    section: "B",
    chapterId: "ch-ekc",
    status: "active",
    isPublic: true,
    skills: ["Mobile Dev", "Flutter", "React Native"],
    interests: ["Cross-platform Apps", "Mobile UX"],
    points: 1650,
    badges: ["Founder", "Mobile Lead"],
    bio: "Founder · Mobile Engineering Lead.",
  },
  {
    id: "usr-arshak",
    fullName: "Arshak",
    email: "arshak@elevates.live",
    avatarUrl: "/images/founders/arshak.png",
    department: "Computer Science & Engineering",
    year: "4th Year",
    section: "B",
    chapterId: "ch-ekc",
    status: "active",
    isPublic: true,
    skills: ["Frontend", "TypeScript", "Next.js"],
    interests: ["Modern Web", "Performance"],
    points: 1600,
    badges: ["Founder", "Frontend Engineer"],
    bio: "Founder · Frontend Engineer.",
  },
  {
    id: "usr-ashith",
    fullName: "Ashith",
    email: "ashith@elevates.live",
    avatarUrl: "/images/founders/ashith.jpeg",
    department: "Mechanical Engineering",
    year: "4th Year",
    section: "A",
    chapterId: "ch-ekc",
    status: "active",
    isPublic: true,
    skills: ["Operations", "Logistics", "Event Management"],
    interests: ["Campus Ops", "Event Production"],
    points: 1700,
    badges: ["Founder", "Operations Lead"],
    bio: "Founder · Operations & Logistics Lead.",
  },
  {
    id: "usr-fiyas",
    fullName: "Muhammed Fiyas",
    email: "fiyas@elevates.live",
    avatarUrl: "/images/founders/fiyas.png",
    department: "Artificial Intelligence & Data Science",
    year: "4th Year",
    section: "A",
    chapterId: "ch-ekc",
    status: "active",
    isPublic: true,
    skills: ["Data Engineering", "Python", "Automation"],
    interests: ["Analytics", "Platform Integrations"],
    points: 1750,
    badges: ["Founder", "Data Lead"],
    bio: "Founder · Data Engineering Lead.",
  },
  {
    id: "usr-haadi",
    fullName: "Haadi",
    email: "haadi@elevates.live",
    avatarUrl: "/images/founders/haadi.jpeg",
    department: "Computer Science & Engineering",
    year: "4th Year",
    section: "A",
    chapterId: "ch-ekc",
    status: "active",
    isPublic: true,
    skills: ["Cloud", "DevOps", "Docker", "Linux"],
    interests: ["Kubernetes", "CI/CD"],
    points: 1800,
    badges: ["Founder", "DevOps Lead"],
    bio: "Founder · DevOps & Cloud Lead.",
  },
  {
    id: "usr-mijvad",
    fullName: "Mohammed Mijvad",
    email: "mijvad@elevates.live",
    avatarUrl: "/images/founders/mijvad.jpeg",
    department: "Mechanical Engineering",
    year: "4th Year",
    section: "A",
    chapterId: "ch-ekc",
    status: "active",
    isPublic: true,
    skills: ["Event Direction", "Quiz Coordination", "Student Outreach"],
    interests: ["Trivia", "Tech Quizzing"],
    points: 1650,
    badges: ["Founder", "Outreach Lead"],
    bio: "Founder · Outreach & Engagement Lead.",
  },
  {
    id: "usr-shahinek",
    fullName: "Shahin EK",
    email: "shahin@elevates.live",
    avatarUrl: "/images/founders/shahin-ek.jpeg",
    department: "Civil Engineering",
    year: "4th Year",
    section: "A",
    chapterId: "ch-ekc",
    status: "active",
    isPublic: true,
    skills: ["Project Management", "Field Operations"],
    interests: ["Infrastructure", "Event Coordination"],
    points: 1550,
    badges: ["Founder", "Field Lead"],
    bio: "Founder · Infrastructure & Field Coordinator.",
  },
  {
    id: "usr-shanif",
    fullName: "Shanif",
    email: "shanif@elevates.live",
    avatarUrl: "/images/founders/shanif.jpeg",
    department: "Computer Science & Engineering",
    year: "4th Year",
    section: "B",
    chapterId: "ch-ekc",
    status: "active",
    isPublic: true,
    skills: ["Media Production", "Photography", "Video Editing"],
    interests: ["Visual Storytelling", "Cinematography"],
    points: 1600,
    badges: ["Founder", "Media Lead"],
    bio: "Founder · Media Production Lead.",
  },
  {
    id: "usr-shifna",
    fullName: "Shifna",
    email: "shifna@elevates.live",
    avatarUrl: "/images/founders/shifna.jpeg",
    department: "Computer Science & Engineering",
    year: "4th Year",
    section: "A",
    chapterId: "ch-ekc",
    status: "active",
    isPublic: true,
    skills: ["Community Management", "Diversity in Tech"],
    interests: ["Mentorship", "Student Growth"],
    points: 1700,
    badges: ["Founder", "Community Lead"],
    bio: "Founder · Community & Mentorship Lead.",
  },
  {
    id: "usr-sinan",
    fullName: "Sinan Nooren",
    email: "sinan@elevates.live",
    avatarUrl: "/images/founders/sinan-nooren.png",
    department: "Computer Science & Engineering",
    year: "4th Year",
    section: "B",
    chapterId: "ch-ekc",
    status: "active",
    isPublic: true,
    skills: ["Backend", "REST APIs", "PostgreSQL"],
    interests: ["Database Design", "API Architecture"],
    points: 1650,
    badges: ["Founder", "Backend Engineer"],
    bio: "Founder · Backend Systems Engineer.",
  },
  {
    id: "usr-sona",
    fullName: "Sona",
    email: "sona@elevates.live",
    avatarUrl: "/images/founders/sona.jpg",
    department: "Computer Science & Engineering",
    year: "4th Year",
    section: "A",
    chapterId: "ch-ekc",
    status: "active",
    isPublic: true,
    skills: ["Public Relations", "Content Strategy", "Copywriting"],
    interests: ["Technical Writing", "Communications"],
    points: 1700,
    badges: ["Founder", "PR Lead"],
    bio: "Founder · Public Relations & Communications Lead.",
  },
  {
    id: "usr-danish",
    fullName: "Danish Gagarin",
    email: "danish@elevates.live",
    avatarUrl: "/images/founders/danish.jpeg",
    department: "Cyber Security",
    year: "2nd Year",
    section: "T2",
    chapterId: "ch-ekc",
    status: "active",
    isPublic: true,
    skills: ["Web Design", "UI/UX", "Bootstrap 5", "HTML/CSS"],
    interests: ["Campus Leadership", "Frontend Engineering"],
    points: 1250,
    badges: ["Chapter Lead", "Workshop Host"],
    bio: "Campus Chapter Lead at Eranad Knowledge City Technical Campus.",
  },
  {
    id: "usr-jasira",
    fullName: "Prof. Jasira KT",
    email: "jasira@ekctc.edu.in",
    avatarUrl: "/images/advisors/jasira-kt.jpeg",
    department: "Computer Science & Engineering",
    chapterId: "ch-ekc",
    status: "active",
    isPublic: true,
    skills: ["Academic Oversight", "Faculty Mentorship"],
    interests: ["Student Innovation", "Curriculum Labs"],
    points: 3000,
    badges: ["Faculty Head", "Advisor"],
    bio: "Faculty Head, CSE at Eranad Knowledge City Technical Campus.",
  },
];

// ── ALL 19 EVENTS FROM ELEVATES-WEB ──────────────────────────────────────────
const chapterEvents: EventItem[] = [
  {
    id: "evt-decode-linkedin",
    chapterId: "ch-ekc",
    title: "LET'S DECODE LINKEDIN",
    bannerEmoji: "💼",
    description: "The LinkedIn Way · Professional Branding, Networking & Internships by Shiju Roy & Mishal V P.",
    venue: "Seminar Hall, Eranad Knowledge City Technical Campus (EKCTC)",
    startsAt: "2026-07-22T10:00:00+05:30",
    endsAt: "2026-07-22T16:00:00+05:30",
    organizerId: "usr-sarhan",
    capacity: 100,
    waitlistCapacity: 20,
    visibility: "all_chapters",
    registrationStart: "2026-07-01T00:00:00+05:30",
    registrationEnd: "2026-07-21T23:59:59+05:30",
    status: "completed",
    certificateEnabled: true,
    ticketNo: "T-LINKEDIN",
    category: "workshop",
    slug: "decode-linkedin-shiju-mishal",
    bannerUrl: "/images/events/decode-linkedin-shiju-mishal.jpeg",
  },
  {
    id: "evt-career-catalyst",
    chapterId: "ch-ekc",
    title: "CAREER CATALYST — WORKSHOP",
    bannerEmoji: "🎯",
    description: "Employability, Resumes & Mock Interviews by Prof. Baiju B S (Placement Head, MEA).",
    venue: "Seminar Hall, EKCTC",
    startsAt: "2026-07-15T10:00:00+05:30",
    endsAt: "2026-07-15T16:00:00+05:30",
    organizerId: "usr-sarhan",
    capacity: 80,
    waitlistCapacity: 15,
    visibility: "all_chapters",
    registrationStart: "2026-07-01T00:00:00+05:30",
    registrationEnd: "2026-07-14T23:59:59+05:30",
    status: "completed",
    certificateEnabled: true,
    ticketNo: "T-CATALYST",
    category: "workshop",
    slug: "career-catalyst-baiju",
    bannerUrl: "/images/events/career-catalyst-baiju.jpeg",
  },
  {
    id: "evt-vibe-coding-brototype",
    chapterId: "ch-ekc",
    title: "VIBE CODING WORKSHOP",
    bannerEmoji: "⚡",
    description: "Rapid Prototyping & AI-assisted development with Brototype mentors Jobin Selvanose & Umar Muqthar.",
    venue: "Seminar Hall, EKCTC",
    startsAt: "2026-03-26T10:00:00+05:30",
    endsAt: "2026-03-26T16:00:00+05:30",
    organizerId: "usr-sarhan",
    capacity: 90,
    waitlistCapacity: 20,
    visibility: "all_chapters",
    registrationStart: "2026-03-15T00:00:00+05:30",
    registrationEnd: "2026-03-25T23:59:59+05:30",
    status: "completed",
    certificateEnabled: true,
    ticketNo: "T-VIBE",
    category: "workshop",
    slug: "vibe-coding-brototype",
    bannerUrl: "/images/events/vibe-coding-brototype.jpeg",
  },
  {
    id: "evt-cse-revamp-mehar",
    chapterId: "ch-ekc",
    title: "REVAMP OF CSE ASSOCIATION (CELESTIA)",
    bannerEmoji: "🚀",
    description: "Association relaunch with Chief Guest Mehar M P (Co-Founder, TinkerHub). Rebuilt portal in 60 minutes with gesture launch.",
    venue: "Seminar Hall, EKCTC",
    startsAt: "2026-03-25T14:00:00+05:30",
    endsAt: "2026-03-25T16:00:00+05:30",
    organizerId: "usr-sarhan",
    capacity: 250,
    waitlistCapacity: 50,
    visibility: "all_chapters",
    registrationStart: "2026-03-10T00:00:00+05:30",
    registrationEnd: "2026-03-24T23:59:59+05:30",
    status: "completed",
    certificateEnabled: true,
    ticketNo: "T-CELESTIA",
    category: "meetup",
    slug: "cse-association-revamp-mehar",
    bannerUrl: "/images/events/cse-association-revamp-mehar.jpeg",
  },
  {
    id: "evt-aids-inauguration",
    chapterId: "ch-ekc",
    title: "AI & DS ASSOCIATION INAUGURATION",
    bannerEmoji: "✨",
    description: "Inauguration ceremony with Elyst AI Co-Founders Fathima Shirin P & Nihal Anas.",
    venue: "Seminar Hall, EKCTC",
    startsAt: "2026-03-12T10:00:00+05:30",
    endsAt: "2026-03-12T13:00:00+05:30",
    organizerId: "usr-sarhan",
    capacity: 100,
    waitlistCapacity: 20,
    visibility: "all_chapters",
    registrationStart: "2026-03-01T00:00:00+05:30",
    registrationEnd: "2026-03-11T23:59:59+05:30",
    status: "completed",
    certificateEnabled: true,
    ticketNo: "T-AIDS",
    category: "meetup",
    slug: "aids-association-inauguration",
    bannerUrl: "/images/events/aids-association-inauguration.jpeg",
  },
  {
    id: "evt-campus-launch",
    chapterId: "ch-ekc",
    title: "ELEVATES CAMPUS LAUNCH",
    bannerEmoji: "🔥",
    description: "Chapter opening with Chief Guest Shibili Rahman KP (Founder & Chairman, RAC Global). 120 seats filled in 2 hours.",
    venue: "Seminar Hall, EKCTC",
    startsAt: "2026-03-04T10:00:00+05:30",
    endsAt: "2026-03-04T13:00:00+05:30",
    organizerId: "usr-sarhan",
    capacity: 120,
    waitlistCapacity: 30,
    visibility: "all_chapters",
    registrationStart: "2026-02-20T00:00:00+05:30",
    registrationEnd: "2026-03-03T23:59:59+05:30",
    status: "completed",
    certificateEnabled: true,
    ticketNo: "T-LAUNCH",
    category: "meetup",
    slug: "elevates-campus-launch-ekctc",
    bannerUrl: "/images/events/campus-launch-ekctc.jpeg",
  },
  {
    id: "evt-basics-of-iot",
    chapterId: "ch-ekc",
    title: "BASICS OF IOT WORKSHOP",
    bannerEmoji: "📡",
    description: "Hands-on sensor interfacing, MQTT & cloud dashboards by Naval K Raj.",
    venue: "Seminar Hall, EKCTC",
    startsAt: "2026-02-19T10:00:00+05:30",
    endsAt: "2026-02-19T16:00:00+05:30",
    organizerId: "usr-sarhan",
    capacity: 40,
    waitlistCapacity: 10,
    visibility: "all_chapters",
    registrationStart: "2026-02-05T00:00:00+05:30",
    registrationEnd: "2026-02-18T23:59:59+05:30",
    status: "completed",
    certificateEnabled: true,
    ticketNo: "T-IOT",
    category: "workshop",
    slug: "basics-of-iot-naval",
    bannerUrl: "/images/events/basics-of-iot-naval.jpeg",
  },
  {
    id: "evt-dgps-survey",
    chapterId: "ch-ekc",
    title: "LAND SURVEY USING DGPS — WORKSHOP",
    bannerEmoji: "🛰️",
    description: "Practical differential GPS geospatial mapping led by Favad (S8 Civil).",
    venue: "EKC Volleyball Court, EKCTC",
    startsAt: "2026-01-19T10:00:00+05:30",
    endsAt: "2026-01-19T13:00:00+05:30",
    organizerId: "usr-sarhan",
    capacity: 40,
    waitlistCapacity: 10,
    visibility: "all_chapters",
    registrationStart: "2026-01-05T00:00:00+05:30",
    registrationEnd: "2026-01-18T23:59:59+05:30",
    status: "completed",
    certificateEnabled: true,
    ticketNo: "T-DGPS",
    category: "workshop",
    slug: "dgps-land-survey-favad",
    bannerUrl: "/images/events/dgps-survey-favad.jpeg",
  },
  {
    id: "evt-modern-web-design",
    chapterId: "ch-ekc",
    title: "MODERN WEB DESIGN WORKSHOP",
    bannerEmoji: "🌐",
    description: "UI/UX, Bootstrap 5, and GitHub Pages live deployment led by Danish Gagarin.",
    venue: "Lab 4, EKCTC",
    startsAt: "2026-01-12T10:00:00+05:30",
    endsAt: "2026-01-12T16:00:00+05:30",
    organizerId: "usr-sarhan",
    capacity: 50,
    waitlistCapacity: 10,
    visibility: "all_chapters",
    registrationStart: "2026-01-01T00:00:00+05:30",
    registrationEnd: "2026-01-11T23:59:59+05:30",
    status: "completed",
    certificateEnabled: true,
    ticketNo: "T-WEBDESIGN",
    category: "workshop",
    slug: "modern-web-design-danish",
    bannerUrl: "/images/events/modern-web-design-danish.jpeg",
  },
  {
    id: "evt-no-code-ai",
    chapterId: "ch-ekc",
    title: "NO-CODE AI & AUTOMATION WORKSHOP",
    bannerEmoji: "🤖",
    description: "n8n automations, LLM chains & webhooks led by Anshiq.",
    venue: "Seminar Hall, EKCTC",
    startsAt: "2026-01-07T10:00:00+05:30",
    endsAt: "2026-01-07T16:00:00+05:30",
    organizerId: "usr-sarhan",
    capacity: 80,
    waitlistCapacity: 15,
    visibility: "all_chapters",
    registrationStart: "2025-12-25T00:00:00+05:30",
    registrationEnd: "2026-01-06T23:59:59+05:30",
    status: "completed",
    certificateEnabled: true,
    ticketNo: "T-NOCODE",
    category: "workshop",
    slug: "no-code-ai-anshiq",
    bannerUrl: "/images/events/no-code-ai-anshiq.jpeg",
  },
  {
    id: "evt-digital-marketing",
    chapterId: "ch-ekc",
    title: "DIGITAL MARKETING WORKSHOP",
    bannerEmoji: "📈",
    description: "Brand Strategy & Ads Analytics by Kalkus Studio (Salim & Anas).",
    venue: "Seminar Hall, EKCTC",
    startsAt: "2025-12-10T10:00:00+05:30",
    endsAt: "2025-12-10T13:00:00+05:30",
    organizerId: "usr-sarhan",
    capacity: 80,
    waitlistCapacity: 15,
    visibility: "all_chapters",
    registrationStart: "2025-12-01T00:00:00+05:30",
    registrationEnd: "2025-12-09T23:59:59+05:30",
    status: "completed",
    certificateEnabled: true,
    ticketNo: "T-MARKETING",
    category: "workshop",
    slug: "digital-marketing-kalkus",
    bannerUrl: "/images/events/digital-marketing-kalkus.jpeg",
  },
  {
    id: "evt-cyber-raid-ctf",
    chapterId: "ch-ekc",
    title: "CYBER RAID — CAPTURE THE FLAG",
    bannerEmoji: "🚩",
    description: "Competitive CTF battle with ₹1500 prize pool led by Adhinan K.",
    venue: "Lab 4, EKCTC",
    startsAt: "2025-10-09T10:00:00+05:30",
    endsAt: "2025-10-09T16:30:00+05:30",
    organizerId: "usr-sarhan",
    capacity: 60,
    waitlistCapacity: 10,
    visibility: "all_chapters",
    registrationStart: "2025-10-01T00:00:00+05:30",
    registrationEnd: "2025-10-08T23:59:59+05:30",
    status: "completed",
    certificateEnabled: true,
    ticketNo: "T-CTF",
    category: "challenge",
    slug: "cyber-raid-ctf",
    bannerUrl: "/images/events/adhinan-ctf.jpeg",
  },
  {
    id: "evt-buzzer-to-buzzer",
    chapterId: "ch-ekc",
    title: "BUZZER TO BUZZER — TECH QUIZ",
    bannerEmoji: "🔔",
    description: "High-stakes head-to-head buzzer quiz battle during Vibranium 5.0 TechFest.",
    venue: "EKCTC",
    startsAt: "2025-10-09T10:00:00+05:30",
    endsAt: "2025-10-09T15:30:00+05:30",
    organizerId: "usr-sarhan",
    capacity: 50,
    waitlistCapacity: 10,
    visibility: "all_chapters",
    registrationStart: "2025-10-01T00:00:00+05:30",
    registrationEnd: "2025-10-08T23:59:59+05:30",
    status: "completed",
    certificateEnabled: true,
    ticketNo: "T-BUZZER",
    category: "challenge",
    slug: "buzzer-to-buzzer",
    bannerUrl: "/images/events/buzzer-to-buzzer.jpeg",
  },
  {
    id: "evt-vibranium-vibe-coding",
    chapterId: "ch-ekc",
    title: "VIBRANIUM 5.0 — VIBE CODING",
    bannerEmoji: "⚡",
    description: "Speed coding challenge & rapid AI prototyping with ₹250 prize pool.",
    venue: "Seminar Hall, EKCTC",
    startsAt: "2025-10-09T10:00:00+05:30",
    endsAt: "2025-10-09T12:00:00+05:30",
    organizerId: "usr-sarhan",
    capacity: 50,
    waitlistCapacity: 10,
    visibility: "all_chapters",
    registrationStart: "2025-10-01T00:00:00+05:30",
    registrationEnd: "2025-10-08T23:59:59+05:30",
    status: "completed",
    certificateEnabled: true,
    ticketNo: "T-VIBECODE",
    category: "challenge",
    slug: "vibranium-vibe-coding",
    bannerUrl: "/images/events/vibe-coding-vibranium.jpeg",
  },
  {
    id: "evt-vibranium-ai-battle",
    chapterId: "ch-ekc",
    title: "VIBRANIUM 5.0 — AI BATTLE ARENA",
    bannerEmoji: "♟️",
    description: "Live LLM chess duels and AI exhibition stall coordinated by Mashood M.",
    venue: "EKCTC",
    startsAt: "2025-10-09T10:00:00+05:30",
    endsAt: "2025-10-09T16:00:00+05:30",
    organizerId: "usr-sarhan",
    capacity: 50,
    waitlistCapacity: 10,
    visibility: "all_chapters",
    registrationStart: "2025-10-01T00:00:00+05:30",
    registrationEnd: "2025-10-08T23:59:59+05:30",
    status: "completed",
    certificateEnabled: true,
    ticketNo: "T-AIBATTLE",
    category: "showcase",
    slug: "vibranium-ai-battle",
    bannerUrl: "/images/events/ai-battle-vibranium.jpeg",
  },
  {
    id: "evt-vibranium-qr-treasure",
    chapterId: "ch-ekc",
    title: "VIBRANIUM 5.0 — QR TREASURE HUNT",
    bannerEmoji: "🗺️",
    description: "Campus-wide cryptographic QR scavenger hunt with algorithmic clues.",
    venue: "EKCTC",
    startsAt: "2025-10-09T10:00:00+05:30",
    endsAt: "2025-10-09T13:30:00+05:30",
    organizerId: "usr-sarhan",
    capacity: 50,
    waitlistCapacity: 10,
    visibility: "all_chapters",
    registrationStart: "2025-10-01T00:00:00+05:30",
    registrationEnd: "2025-10-08T23:59:59+05:30",
    status: "completed",
    certificateEnabled: true,
    ticketNo: "T-QRTREASURE",
    category: "challenge",
    slug: "vibranium-qr-treasure-hunt",
    bannerUrl: "/images/events/qr-tressure-hunt-vibranium.jpeg",
  },
  {
    id: "evt-first-spark",
    chapterId: "ch-ekc",
    title: "FIRST SPARK — BASICS OF ELECTRONICS",
    bannerEmoji: "💡",
    description: "Circuit fundamentals, passive components & semiconductors by Sahad Nisham K.",
    venue: "ECE Digital Lab, EKCTC",
    startsAt: "2025-09-26T10:00:00+05:30",
    endsAt: "2025-09-26T16:00:00+05:30",
    organizerId: "usr-sarhan",
    capacity: 40,
    waitlistCapacity: 10,
    visibility: "all_chapters",
    registrationStart: "2025-09-15T00:00:00+05:30",
    registrationEnd: "2025-09-25T23:59:59+05:30",
    status: "completed",
    certificateEnabled: true,
    ticketNo: "T-SPARK",
    category: "workshop",
    slug: "first-spark-electronics",
    bannerUrl: "/images/events/spark-sahad-nisham.jpeg",
  },
  {
    id: "evt-stap-assessment",
    chapterId: "ch-ekc",
    title: "STAP — SKILL TASTE ASSESSMENT",
    bannerEmoji: "📊",
    description: "Hands-on AI, Data & UI/UX portfolio assessment with Skilltrai Freelance Academy.",
    venue: "Seminar Hall, EKCTC",
    startsAt: "2025-09-22T14:00:00+05:30",
    endsAt: "2025-09-22T17:30:00+05:30",
    organizerId: "usr-sarhan",
    capacity: 90,
    waitlistCapacity: 20,
    visibility: "all_chapters",
    registrationStart: "2025-09-10T00:00:00+05:30",
    registrationEnd: "2025-09-21T23:59:59+05:30",
    status: "completed",
    certificateEnabled: true,
    ticketNo: "T-STAP",
    category: "workshop",
    slug: "stap-skill-assessment",
    bannerUrl: "/images/events/stap-by-skilltrai.jpeg",
  },
  {
    id: "evt-cybersec-basics",
    chapterId: "ch-ekc",
    title: "CYBERSECURITY WORKSHOP",
    bannerEmoji: "🛡️",
    description: "3-Phase Kali Linux & practical network defense workshop led by Adhinan K.",
    venue: "Seminar Hall, EKCTC",
    startsAt: "2025-09-17T10:00:00+05:30",
    endsAt: "2025-09-25T16:10:00+05:30",
    organizerId: "usr-sarhan",
    capacity: 90,
    waitlistCapacity: 20,
    visibility: "all_chapters",
    registrationStart: "2025-09-01T00:00:00+05:30",
    registrationEnd: "2025-09-16T23:59:59+05:30",
    status: "completed",
    certificateEnabled: true,
    ticketNo: "T-CYBERSEC",
    category: "workshop",
    slug: "cybersec-basics",
    bannerUrl: "/images/events/cybersecurity-workshop.jpeg",
  },
];

export function createSeedStore(): ElevatesStore {
  return {
    organization: {
      id: "org-1",
      name: "Elevates Foundation",
      slug: "elevates",
      tagline: "Engineering Culture, Open Building & Tech Leadership across Campuses",
      brandKit: {
        logoUrl: "/elevates-mark.svg",
        colors: {
          accent: "#f26430",
          charcoal: "#2d2d34",
          sage: "#5f7560",
          indigo: "#414066",
        },
      },
    },
    chapters: [
      {
        id: "ch-ekc",
        organizationId: "org-1",
        name: "Eranad Knowledge City Chapter",
        slug: "ekc",
        college: "Eranad Knowledge City Technical Campus",
        city: "Manjeri",
        district: "Malappuram",
        status: "active",
        healthScore: 98,
        memberCount: 128,
        eventCount: 19,
        projectCount: 4,
        foundedAt: "2025-09-01T00:00:00Z",
        published: true,
        notes: "Chapter #01 · Founded September 2025 by 18 founding members.",
      },
    ],
    profiles: defaultProfiles,
    roles,
    permissions,
    rolePermissions,
    userRoles: [
      { id: "ur-1", userId: "usr-sarhan", roleId: "r-founder", chapterId: "ch-ekc", organizationId: "org-1" },
      { id: "ur-2", userId: "usr-danish", roleId: "r-chairman", chapterId: "ch-ekc", organizationId: "org-1" },
      { id: "ur-3", userId: "usr-jasira", roleId: "r-faculty", chapterId: "ch-ekc", organizationId: "org-1" },
    ],
    departments: [
      { id: "dept-1", chapterId: "ch-ekc", name: "Computer Science & Engineering" },
      { id: "dept-2", chapterId: "ch-ekc", name: "Cyber Security" },
      { id: "dept-3", chapterId: "ch-ekc", name: "Artificial Intelligence & Data Science" },
      { id: "dept-4", chapterId: "ch-ekc", name: "Computer Science & Business Systems" },
      { id: "dept-5", chapterId: "ch-ekc", name: "Civil Engineering" },
      { id: "dept-6", chapterId: "ch-ekc", name: "Mechanical Engineering" },
      { id: "dept-7", chapterId: "ch-ekc", name: "Electronics & Communication" },
    ],
    classCohorts: [
      { id: "cc-1", chapterId: "ch-ekc", department: "Computer Science & Engineering", year: "4", section: "A", repIds: ["usr-sarhan", "usr-naseem"] },
      { id: "cc-2", chapterId: "ch-ekc", department: "Cyber Security", year: "2", section: "T2", repIds: ["usr-danish"] },
    ],
    leadershipTerms: [
      {
        id: "term-2025-26",
        chapterId: "ch-ekc",
        academicYear: "2025-26",
        title: "Inaugural Leadership Term (2025-26)",
        startDate: "2025-09-01",
        endDate: "2026-08-31",
        status: "active",
        handoverNotes: "Official founding term established by the 18 founding members.",
      },
    ],
    leadershipAssignments: [
      { id: "la-1", termId: "term-2025-26", userId: "usr-danish", roleKey: "chairman", title: "Campus Chapter Lead" },
      { id: "la-2", termId: "term-2025-26", userId: "usr-jasira", roleKey: "faculty_coordinator", title: "Faculty Head, CSE" },
    ],
    events: chapterEvents,
    eventForms: [],
    forms: [],
    formResponses: [],
    registrations: [],
    attendance: [],
    certificates: [],
    clusters: [
      { id: "cl-1", chapterId: "ch-ekc", name: "Full-Stack Web & Systems", slug: "fullstack", accessMode: "open", description: "Next.js, Postgres & Edge deployments", memberIds: ["usr-sarhan"], roadmap: [] },
      { id: "cl-2", chapterId: "ch-ekc", name: "Cybersecurity & Network Defense", slug: "cybersec", accessMode: "open", description: "Kali Linux, CTF & Security Audits", memberIds: ["usr-danish", "usr-adhinan"], roadmap: [] },
      { id: "cl-3", chapterId: "ch-ekc", name: "AI Automation & Agents", slug: "ai-agents", accessMode: "open", description: "n8n, LLMs & Automation Workflows", memberIds: ["usr-mashood", "usr-sarhan"], roadmap: [] },
    ],
    projects: [
      { id: "p-vib", chapterId: "ch-ekc", title: "Vibranium Event Platform", stage: "showcase", projectType: "campus", description: "400k requests in 24h with zero downtime.", teamIds: ["usr-sarhan", "usr-naseem"], progress: 100, awards: ["Flagship Fest Engine"] },
      { id: "p-aar", chapterId: "ch-ekc", title: "Aaroh Arts Platform", stage: "showcase", projectType: "campus", description: "Arts fest scoring engine for 50+ events.", teamIds: ["usr-sarhan", "usr-nafih"], progress: 100, awards: [] },
      { id: "p-cel", chapterId: "ch-ekc", title: "Celestia Department Portal", stage: "demo", projectType: "campus", description: "Rebuilt live in 1 hour on stage with gesture launch.", teamIds: ["usr-sarhan", "usr-danish"], progress: 100, awards: ["1-Hour Stage Build"] },
      { id: "p-road", chapterId: "ch-ekc", title: "RoadUndo Pincode API", stage: "showcase", projectType: "open_source", description: "Open postal route engine across 5,057 Kerala pincodes.", teamIds: ["usr-sarhan"], progress: 100, awards: ["Open Tool"] },
    ],
    resourceCategories: [],
    resources: [],
    guidelines: [],
    tasks: [],
    reports: [],
    announcements: [],
    outboundMessages: [],
    notifications: [],
    activityLogs: [],
    clusterInvites: [],
    leadershipApplications: [],
    chapterStandardChecks: [],
    session: {
      userId: "usr-sarhan",
      roleKey: "founder",
      chapterId: "ch-ekc",
    },
  };
}
